-- 20260602000002_seed_component_registry.up.sql
-- Seeds the ui_component_registry with 76 platform components.

INSERT INTO ui_component_registry (component_code, component_name, category, version, source, supported_surfaces, supported_bindings, is_container, allowed_parents, allowed_children, config_schema, default_props, event_support, permission_behavior, runtime_renderer, designer_panel, preview_support, validation_rules)
VALUES
-- ═══════════════════════════════════════════════════════════════════════════════
-- LAYOUT (12)
-- ═══════════════════════════════════════════════════════════════════════════════
('page_root', 'Page Root', 'layout', '1.0.0', 'platform',
 '["all"]', '[]', true, '[]', '["section","tab_container","grid_row","card","accordion","split_pane","drawer_panel","modal_container","wizard_step_container","header_line_section","form_section","repeater","conditional_container"]',
 '{"properties":{"title":{"type":"string"},"layout":{"type":"string","enum":["full","centered","sidebar"]},"padding":{"type":"string","enum":["none","sm","md","lg"]}}}',
 '{"layout":"full","padding":"md"}',
 '{"emits":["on_load"],"handles":[]}',
 '{"hidden_action":"remove_from_dom"}',
 'PageRootRenderer', 'PageRootPanel', true, '[]'),

('section', 'Section', 'layout', '1.0.0', 'platform',
 '["all"]', '[]', true, '["page_root","tab_panel","grid_column","card","accordion","split_pane","wizard_step_container","repeater","conditional_container"]', '["all"]',
 '{"properties":{"title":{"type":"string"},"collapsible":{"type":"boolean"},"collapsed_default":{"type":"boolean"},"columns":{"type":"integer","minimum":1,"maximum":4}}}',
 '{"collapsible":false,"collapsed_default":false,"columns":1}',
 '{"emits":["on_click"],"handles":["show","hide"]}',
 '{}', 'SectionRenderer', 'SectionPanel', true, '[]'),

('tab_container', 'Tab Container', 'layout', '1.0.0', 'platform',
 '["all"]', '[]', true, '["page_root","section","grid_column","card","split_pane"]', '["tab_panel"]',
 '{"properties":{"orientation":{"type":"string","enum":["horizontal","vertical"]},"default_tab":{"type":"string"}}}',
 '{"orientation":"horizontal"}',
 '{"emits":["on_change"],"handles":[]}',
 '{}', 'TabContainerRenderer', 'TabContainerPanel', true, '[]'),

('tab_panel', 'Tab Panel', 'layout', '1.0.0', 'platform',
 '["all"]', '[]', true, '["tab_container"]', '["all"]',
 '{"properties":{"label":{"type":"string"},"icon":{"type":"string"},"disabled":{"type":"boolean"}}}',
 '{"disabled":false}',
 '{"emits":[],"handles":["show","hide"]}',
 '{}', 'TabPanelRenderer', 'TabPanelPanel', true, '[]'),

('grid_row', 'Grid Row', 'layout', '1.0.0', 'platform',
 '["all"]', '[]', true, '["page_root","section","tab_panel","card","accordion","wizard_step_container","repeater","conditional_container"]', '["grid_column"]',
 '{"properties":{"gap":{"type":"string","enum":["none","sm","md","lg"]},"align":{"type":"string","enum":["start","center","end","stretch"]}}}',
 '{"gap":"md","align":"stretch"}',
 '{"emits":[],"handles":[]}',
 '{}', 'GridRowRenderer', 'GridRowPanel', true, '[]'),

('grid_column', 'Grid Column', 'layout', '1.0.0', 'platform',
 '["all"]', '[]', true, '["grid_row"]', '["all"]',
 '{"properties":{"span":{"type":"integer","minimum":1,"maximum":12},"span_md":{"type":"integer"},"span_sm":{"type":"integer"}}}',
 '{"span":6}',
 '{"emits":[],"handles":[]}',
 '{}', 'GridColumnRenderer', 'GridColumnPanel', true, '[]'),

('card', 'Card', 'layout', '1.0.0', 'platform',
 '["all"]', '[]', true, '["page_root","section","tab_panel","grid_column","split_pane","repeater","conditional_container"]', '["all"]',
 '{"properties":{"title":{"type":"string"},"subtitle":{"type":"string"},"elevation":{"type":"string","enum":["flat","low","medium","high"]},"padding":{"type":"string","enum":["none","sm","md","lg"]}}}',
 '{"elevation":"low","padding":"md"}',
 '{"emits":["on_click"],"handles":["show","hide"]}',
 '{}', 'CardRenderer', 'CardPanel', true, '[]'),

('accordion', 'Accordion', 'layout', '1.0.0', 'platform',
 '["all"]', '[]', true, '["page_root","section","tab_panel","grid_column","card"]', '["all"]',
 '{"properties":{"title":{"type":"string"},"expanded_default":{"type":"boolean"},"icon":{"type":"string"}}}',
 '{"expanded_default":false}',
 '{"emits":["on_change"],"handles":["expand","collapse"]}',
 '{}', 'AccordionRenderer', 'AccordionPanel', true, '[]'),

('split_pane', 'Split Pane', 'layout', '1.0.0', 'platform',
 '["split_view","advanced_crud","detail_page"]', '[]', true, '["page_root","section","tab_panel"]', '["all"]',
 '{"properties":{"orientation":{"type":"string","enum":["horizontal","vertical"]},"initial_ratio":{"type":"number","minimum":0.1,"maximum":0.9},"resizable":{"type":"boolean"}}}',
 '{"orientation":"horizontal","initial_ratio":0.5,"resizable":true}',
 '{"emits":[],"handles":[]}',
 '{}', 'SplitPaneRenderer', 'SplitPanePanel', true, '[]'),

('drawer_panel', 'Drawer Panel', 'layout', '1.0.0', 'platform',
 '["all"]', '[]', true, '["page_root"]', '["all"]',
 '{"properties":{"position":{"type":"string","enum":["left","right","bottom"]},"width":{"type":"string"},"overlay":{"type":"boolean"}}}',
 '{"position":"right","width":"400px","overlay":true}',
 '{"emits":["on_modal_open","on_modal_close"],"handles":["open","close"]}',
 '{}', 'DrawerPanelRenderer', 'DrawerPanelPanel', true, '[]'),

('modal_container', 'Modal Container', 'layout', '1.0.0', 'platform',
 '["all"]', '[]', true, '["page_root"]', '["all"]',
 '{"properties":{"title":{"type":"string"},"size":{"type":"string","enum":["sm","md","lg","xl","full"]},"closable":{"type":"boolean"},"backdrop_close":{"type":"boolean"}}}',
 '{"size":"md","closable":true,"backdrop_close":true}',
 '{"emits":["on_modal_open","on_modal_close"],"handles":["open","close"]}',
 '{}', 'ModalContainerRenderer', 'ModalContainerPanel', true, '[]'),

('wizard_step_container', 'Wizard Step Container', 'layout', '1.0.0', 'platform',
 '["wizard"]', '[]', true, '["page_root"]', '["all"]',
 '{"properties":{"step_label":{"type":"string"},"step_description":{"type":"string"},"icon":{"type":"string"},"validation_required":{"type":"boolean"}}}',
 '{"validation_required":true}',
 '{"emits":["on_validate"],"handles":["next","prev","goto"]}',
 '{}', 'WizardStepRenderer', 'WizardStepPanel', true, '[]'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- INPUT (22)
-- ═══════════════════════════════════════════════════════════════════════════════
('text_input', 'Text Input', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"placeholder":{"type":"string"},"max_length":{"type":"integer"},"pattern":{"type":"string"},"prefix":{"type":"string"},"suffix":{"type":"string"},"input_type":{"type":"string","enum":["text","email","url","tel","password"]}}}',
 '{"input_type":"text"}',
 '{"emits":["on_change","on_focus","on_blur","on_validate"],"handles":["set_value","clear","focus","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'TextInputRenderer', 'TextInputPanel', true,
 '[{"rule":"required_if_bound","message":"Bound field must have a label"}]'),

('number_input', 'Number Input', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"placeholder":{"type":"string"},"min":{"type":"number"},"max":{"type":"number"},"step":{"type":"number"},"decimal_places":{"type":"integer"},"show_stepper":{"type":"boolean"}}}',
 '{"step":1,"show_stepper":false}',
 '{"emits":["on_change","on_focus","on_blur","on_validate"],"handles":["set_value","clear","focus","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'NumberInputRenderer', 'NumberInputPanel', true, '[]'),

('currency_input', 'Currency Input', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"currency_code":{"type":"string"},"decimal_places":{"type":"integer"},"show_symbol":{"type":"boolean"},"min":{"type":"number"},"max":{"type":"number"}}}',
 '{"currency_code":"USD","decimal_places":2,"show_symbol":true}',
 '{"emits":["on_change","on_focus","on_blur","on_validate"],"handles":["set_value","clear","focus","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'CurrencyInputRenderer', 'CurrencyInputPanel', true, '[]'),

('date_picker', 'Date Picker', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"format":{"type":"string"},"min_date":{"type":"string"},"max_date":{"type":"string"},"disable_past":{"type":"boolean"},"disable_future":{"type":"boolean"}}}',
 '{"format":"YYYY-MM-DD","disable_past":false,"disable_future":false}',
 '{"emits":["on_change","on_focus","on_blur"],"handles":["set_value","clear","focus","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'DatePickerRenderer', 'DatePickerPanel', true, '[]'),

('time_picker', 'Time Picker', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"format":{"type":"string","enum":["12h","24h"]},"step_minutes":{"type":"integer"}}}',
 '{"format":"24h","step_minutes":15}',
 '{"emits":["on_change","on_focus","on_blur"],"handles":["set_value","clear","focus","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'TimePickerRenderer', 'TimePickerPanel', true, '[]'),

('datetime_picker', 'DateTime Picker', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"date_format":{"type":"string"},"time_format":{"type":"string","enum":["12h","24h"]},"min":{"type":"string"},"max":{"type":"string"}}}',
 '{"date_format":"YYYY-MM-DD","time_format":"24h"}',
 '{"emits":["on_change","on_focus","on_blur"],"handles":["set_value","clear","focus","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'DateTimePickerRenderer', 'DateTimePickerPanel', true, '[]'),

('dropdown_select', 'Dropdown Select', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"placeholder":{"type":"string"},"options_source":{"type":"string","enum":["static","entity","expression"]},"static_options":{"type":"array"},"searchable":{"type":"boolean"},"clearable":{"type":"boolean"}}}',
 '{"options_source":"static","searchable":true,"clearable":true}',
 '{"emits":["on_change","on_focus","on_blur"],"handles":["set_value","clear","focus","disable","enable","set_options"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'DropdownSelectRenderer', 'DropdownSelectPanel', true, '[]'),

('multi_select', 'Multi Select', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"placeholder":{"type":"string"},"options_source":{"type":"string","enum":["static","entity","expression"]},"static_options":{"type":"array"},"max_selections":{"type":"integer"},"searchable":{"type":"boolean"}}}',
 '{"options_source":"static","searchable":true}',
 '{"emits":["on_change","on_focus","on_blur"],"handles":["set_value","clear","focus","disable","enable","set_options"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'MultiSelectRenderer', 'MultiSelectPanel', true, '[]'),

('checkbox', 'Checkbox', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"description":{"type":"string"}}}',
 '{}',
 '{"emits":["on_change"],"handles":["set_value","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'CheckboxRenderer', 'CheckboxPanel', true, '[]'),

('checkbox_group', 'Checkbox Group', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"options":{"type":"array"},"orientation":{"type":"string","enum":["horizontal","vertical"]},"max_selections":{"type":"integer"}}}',
 '{"orientation":"vertical"}',
 '{"emits":["on_change"],"handles":["set_value","clear","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'CheckboxGroupRenderer', 'CheckboxGroupPanel', true, '[]'),

('radio_group', 'Radio Group', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"options":{"type":"array"},"orientation":{"type":"string","enum":["horizontal","vertical"]}}}',
 '{"orientation":"vertical"}',
 '{"emits":["on_change"],"handles":["set_value","clear","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'RadioGroupRenderer', 'RadioGroupPanel', true, '[]'),

('toggle_switch', 'Toggle Switch', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"on_label":{"type":"string"},"off_label":{"type":"string"}}}',
 '{}',
 '{"emits":["on_change"],"handles":["set_value","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'ToggleSwitchRenderer', 'ToggleSwitchPanel', true, '[]'),

('textarea', 'Text Area', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","repeater","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"placeholder":{"type":"string"},"rows":{"type":"integer","minimum":2,"maximum":20},"max_length":{"type":"integer"},"resizable":{"type":"boolean"}}}',
 '{"rows":4,"resizable":true}',
 '{"emits":["on_change","on_focus","on_blur","on_validate"],"handles":["set_value","clear","focus","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'TextareaRenderer', 'TextareaPanel', true, '[]'),

('rich_text_editor', 'Rich Text Editor', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"toolbar":{"type":"array"},"max_length":{"type":"integer"},"height":{"type":"string"}}}',
 '{"toolbar":["bold","italic","underline","link","list","heading"],"height":"200px"}',
 '{"emits":["on_change","on_focus","on_blur"],"handles":["set_value","clear","focus","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'RichTextEditorRenderer', 'RichTextEditorPanel', true, '[]'),

('file_upload', 'File Upload', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"accept":{"type":"string"},"max_size_mb":{"type":"number"},"multiple":{"type":"boolean"},"max_files":{"type":"integer"}}}',
 '{"max_size_mb":10,"multiple":false}',
 '{"emits":["on_change","on_validate"],"handles":["clear","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'FileUploadRenderer', 'FileUploadPanel', true, '[]'),

('slider_range', 'Slider / Range', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"min":{"type":"number"},"max":{"type":"number"},"step":{"type":"number"},"range":{"type":"boolean"},"show_value":{"type":"boolean"}}}',
 '{"min":0,"max":100,"step":1,"range":false,"show_value":true}',
 '{"emits":["on_change"],"handles":["set_value","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'SliderRangeRenderer', 'SliderRangePanel', true, '[]'),

('tag_input', 'Tag Input', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"placeholder":{"type":"string"},"max_tags":{"type":"integer"},"allow_custom":{"type":"boolean"},"suggestions":{"type":"array"}}}',
 '{"allow_custom":true}',
 '{"emits":["on_change"],"handles":["set_value","clear","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'TagInputRenderer', 'TagInputPanel', true, '[]'),

('address_block', 'Address Block', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","form_section","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"fields":{"type":"array","items":{"type":"string","enum":["line1","line2","city","state","zip","country"]}},"country_list":{"type":"string","enum":["all","limited"]}}}',
 '{"fields":["line1","line2","city","state","zip","country"]}',
 '{"emits":["on_change","on_validate"],"handles":["set_value","clear","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'AddressBlockRenderer', 'AddressBlockPanel', true, '[]'),

('phone_input', 'Phone Input', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"default_country":{"type":"string"},"show_country_code":{"type":"boolean"},"format":{"type":"string","enum":["national","international","e164"]}}}',
 '{"show_country_code":true,"format":"international"}',
 '{"emits":["on_change","on_focus","on_blur","on_validate"],"handles":["set_value","clear","focus","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'PhoneInputRenderer', 'PhoneInputPanel', true, '[]'),

('code_editor', 'Code Editor', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"language":{"type":"string"},"height":{"type":"string"},"line_numbers":{"type":"boolean"},"read_only":{"type":"boolean"}}}',
 '{"language":"json","height":"300px","line_numbers":true,"read_only":false}',
 '{"emits":["on_change","on_focus","on_blur"],"handles":["set_value","clear","focus","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'CodeEditorRenderer', 'CodeEditorPanel', true, '[]'),

('stepper_input', 'Stepper Input', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"min":{"type":"number"},"max":{"type":"number"},"step":{"type":"number"}}}',
 '{"min":0,"max":100,"step":1}',
 '{"emits":["on_change"],"handles":["set_value","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'StepperInputRenderer', 'StepperInputPanel', true, '[]'),

('color_picker', 'Color Picker', 'input', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"format":{"type":"string","enum":["hex","rgb","hsl"]},"presets":{"type":"array"},"allow_custom":{"type":"boolean"}}}',
 '{"format":"hex","allow_custom":true}',
 '{"emits":["on_change"],"handles":["set_value","clear","disable","enable"]}',
 '{"hidden_action":"remove_from_dom","readonly_action":"disable"}',
 'ColorPickerRenderer', 'ColorPickerPanel', true, '[]'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- DISPLAY (16)
-- ═══════════════════════════════════════════════════════════════════════════════
('label', 'Label', 'display', '1.0.0', 'platform',
 '["all"]', '["field","static"]', false, '["section","grid_column","card","accordion","form_section","tab_panel","repeater"]', '[]',
 '{"properties":{"text":{"type":"string"},"variant":{"type":"string","enum":["default","muted","strong","error"]},"size":{"type":"string","enum":["xs","sm","md","lg"]}}}',
 '{"variant":"default","size":"md"}',
 '{"emits":[],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'LabelRenderer', 'LabelPanel', true, '[]'),

('heading', 'Heading', 'display', '1.0.0', 'platform',
 '["all"]', '["field","static"]', false, '["section","grid_column","card","accordion","form_section","tab_panel"]', '[]',
 '{"properties":{"text":{"type":"string"},"level":{"type":"integer","minimum":1,"maximum":6},"align":{"type":"string","enum":["left","center","right"]}}}',
 '{"level":2,"align":"left"}',
 '{"emits":[],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'HeadingRenderer', 'HeadingPanel', true, '[]'),

('paragraph', 'Paragraph', 'display', '1.0.0', 'platform',
 '["all"]', '["field","static"]', false, '["section","grid_column","card","accordion","form_section","tab_panel"]', '[]',
 '{"properties":{"text":{"type":"string"},"max_lines":{"type":"integer"},"expandable":{"type":"boolean"}}}',
 '{"expandable":false}',
 '{"emits":[],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'ParagraphRenderer', 'ParagraphPanel', true, '[]'),

('badge', 'Badge', 'display', '1.0.0', 'platform',
 '["all"]', '["field","static"]', false, '["section","grid_column","card","accordion","form_section","tab_panel","toolbar"]', '[]',
 '{"properties":{"text":{"type":"string"},"variant":{"type":"string","enum":["default","primary","success","warning","error","info"]},"size":{"type":"string","enum":["sm","md","lg"]}}}',
 '{"variant":"default","size":"md"}',
 '{"emits":[],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'BadgeRenderer', 'BadgePanel', true, '[]'),

('status_badge', 'Status Badge', 'display', '1.0.0', 'platform',
 '["all"]', '["field"]', false, '["section","grid_column","card","accordion","form_section","tab_panel","toolbar","data_table"]', '[]',
 '{"properties":{"status_map":{"type":"object","description":"Maps values to colors/labels"},"show_dot":{"type":"boolean"}}}',
 '{"show_dot":true}',
 '{"emits":[],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'StatusBadgeRenderer', 'StatusBadgePanel', true, '[]'),

('avatar', 'Avatar', 'display', '1.0.0', 'platform',
 '["all"]', '["field","static"]', false, '["section","grid_column","card","accordion","form_section","tab_panel","toolbar"]', '[]',
 '{"properties":{"size":{"type":"string","enum":["xs","sm","md","lg","xl"]},"shape":{"type":"string","enum":["circle","square"]},"fallback":{"type":"string","enum":["initials","icon"]}}}',
 '{"size":"md","shape":"circle","fallback":"initials"}',
 '{"emits":["on_click"],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'AvatarRenderer', 'AvatarPanel', true, '[]'),

('icon', 'Icon', 'display', '1.0.0', 'platform',
 '["all"]', '["static"]', false, '["section","grid_column","card","accordion","form_section","tab_panel","toolbar","button"]', '[]',
 '{"properties":{"name":{"type":"string"},"size":{"type":"string","enum":["xs","sm","md","lg","xl"]},"color":{"type":"string"}}}',
 '{"size":"md"}',
 '{"emits":["on_click"],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'IconRenderer', 'IconPanel', true, '[]'),

('image', 'Image', 'display', '1.0.0', 'platform',
 '["all"]', '["field","static"]', false, '["section","grid_column","card","accordion","tab_panel"]', '[]',
 '{"properties":{"src":{"type":"string"},"alt":{"type":"string"},"width":{"type":"string"},"height":{"type":"string"},"fit":{"type":"string","enum":["cover","contain","fill","none"]},"rounded":{"type":"boolean"}}}',
 '{"fit":"cover","rounded":false}',
 '{"emits":["on_click"],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'ImageRenderer', 'ImagePanel', true, '[]'),

('divider', 'Divider', 'display', '1.0.0', 'platform',
 '["all"]', '[]', false, '["section","grid_column","card","accordion","form_section","tab_panel"]', '[]',
 '{"properties":{"orientation":{"type":"string","enum":["horizontal","vertical"]},"label":{"type":"string"},"thickness":{"type":"string","enum":["thin","normal","thick"]}}}',
 '{"orientation":"horizontal","thickness":"normal"}',
 '{"emits":[],"handles":[]}',
 '{}', 'DividerRenderer', 'DividerPanel', true, '[]'),

('spacer', 'Spacer', 'display', '1.0.0', 'platform',
 '["all"]', '[]', false, '["section","grid_column","card","accordion","form_section","tab_panel","grid_row"]', '[]',
 '{"properties":{"size":{"type":"string","enum":["xs","sm","md","lg","xl","2xl"]}}}',
 '{"size":"md"}',
 '{"emits":[],"handles":[]}',
 '{}', 'SpacerRenderer', 'SpacerPanel', true, '[]'),

('progress_bar', 'Progress Bar', 'display', '1.0.0', 'platform',
 '["all"]', '["field","expression"]', false, '["section","grid_column","card","accordion","form_section","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"max":{"type":"number"},"show_percentage":{"type":"boolean"},"color":{"type":"string","enum":["default","success","warning","error"]},"animated":{"type":"boolean"}}}',
 '{"max":100,"show_percentage":true,"color":"default","animated":false}',
 '{"emits":[],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'ProgressBarRenderer', 'ProgressBarPanel', true, '[]'),

('color_indicator', 'Color Indicator', 'display', '1.0.0', 'platform',
 '["all"]', '["field","static"]', false, '["section","grid_column","card","accordion","form_section","tab_panel","data_table"]', '[]',
 '{"properties":{"shape":{"type":"string","enum":["circle","square","pill"]},"size":{"type":"string","enum":["sm","md","lg"]},"show_value":{"type":"boolean"}}}',
 '{"shape":"circle","size":"md","show_value":false}',
 '{"emits":[],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'ColorIndicatorRenderer', 'ColorIndicatorPanel', true, '[]'),

('timer_countdown', 'Timer / Countdown', 'display', '1.0.0', 'platform',
 '["all"]', '["field","expression"]', false, '["section","grid_column","card","tab_panel","toolbar"]', '[]',
 '{"properties":{"format":{"type":"string","enum":["hh:mm:ss","mm:ss","days_hours"]},"target_field":{"type":"string"},"show_label":{"type":"boolean"},"warn_threshold_seconds":{"type":"integer"}}}',
 '{"format":"hh:mm:ss","show_label":true}',
 '{"emits":["on_change"],"handles":["start","stop","reset","show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'TimerCountdownRenderer', 'TimerCountdownPanel', true, '[]'),

('copy_field', 'Copy Field', 'display', '1.0.0', 'platform',
 '["all"]', '["field","static"]', false, '["section","grid_column","card","accordion","form_section","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"truncate":{"type":"boolean"},"success_message":{"type":"string"}}}',
 '{"truncate":true,"success_message":"Copied!"}',
 '{"emits":["on_click"],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'CopyFieldRenderer', 'CopyFieldPanel', true, '[]'),

('empty_state', 'Empty State', 'display', '1.0.0', 'platform',
 '["all"]', '[]', false, '["section","grid_column","card","tab_panel","page_root"]', '["button"]',
 '{"properties":{"icon":{"type":"string"},"title":{"type":"string"},"description":{"type":"string"},"action_label":{"type":"string"}}}',
 '{}',
 '{"emits":["on_click"],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'EmptyStateRenderer', 'EmptyStatePanel', true, '[]'),

('alert_banner', 'Alert Banner', 'display', '1.0.0', 'platform',
 '["all"]', '[]', false, '["page_root","section","grid_column","card","tab_panel"]', '[]',
 '{"properties":{"variant":{"type":"string","enum":["info","success","warning","error"]},"title":{"type":"string"},"message":{"type":"string"},"dismissible":{"type":"boolean"},"icon":{"type":"string"}}}',
 '{"variant":"info","dismissible":true}',
 '{"emits":["on_click"],"handles":["show","hide","dismiss"]}',
 '{"hidden_action":"remove_from_dom"}',
 'AlertBannerRenderer', 'AlertBannerPanel', true, '[]'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- DATA (8)
-- ═══════════════════════════════════════════════════════════════════════════════
('data_table', 'Data Table', 'data', '1.0.0', 'platform',
 '["standard_crud","advanced_crud","header_line","dashboard","detail_page","split_view"]', '["field"]', true,
 '["section","grid_column","card","tab_panel","split_pane","page_root"]', '[]',
 '{"properties":{"columns":{"type":"array"},"row_actions":{"type":"array"},"selectable":{"type":"boolean"},"selection_mode":{"type":"string","enum":["single","multi"]},"sortable":{"type":"boolean"},"filterable":{"type":"boolean"},"page_size":{"type":"integer"},"striped":{"type":"boolean"},"dense":{"type":"boolean"},"virtual_scroll":{"type":"boolean"}}}',
 '{"selectable":false,"sortable":true,"filterable":false,"page_size":25,"striped":false,"dense":false,"virtual_scroll":false}',
 '{"emits":["on_row_select","on_click","on_change"],"handles":["refresh","set_filter","clear_filter"]}',
 '{"hidden_action":"remove_from_dom"}',
 'DataTableRenderer', 'DataTablePanel', true, '[]'),

('data_card_grid', 'Data Card Grid', 'data', '1.0.0', 'platform',
 '["standard_crud","advanced_crud","dashboard","detail_page"]', '["field"]', true,
 '["section","grid_column","card","tab_panel","page_root"]', '[]',
 '{"properties":{"columns":{"type":"integer","minimum":1,"maximum":6},"card_template":{"type":"object"},"selectable":{"type":"boolean"},"page_size":{"type":"integer"}}}',
 '{"columns":3,"selectable":false,"page_size":12}',
 '{"emits":["on_row_select","on_click"],"handles":["refresh","set_filter"]}',
 '{"hidden_action":"remove_from_dom"}',
 'DataCardGridRenderer', 'DataCardGridPanel', true, '[]'),

('metric_comparison', 'Metric Comparison', 'data', '1.0.0', 'platform',
 '["dashboard","detail_page"]', '["field","expression"]', false,
 '["section","grid_column","card","tab_panel"]', '[]',
 '{"properties":{"label":{"type":"string"},"current_value_source":{"type":"string"},"compare_value_source":{"type":"string"},"format":{"type":"string","enum":["number","percentage","currency"]},"trend_direction":{"type":"string","enum":["up_good","down_good"]}}}',
 '{"format":"number","trend_direction":"up_good"}',
 '{"emits":[],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'MetricComparisonRenderer', 'MetricComparisonPanel', true, '[]'),

('related_list', 'Related List', 'data', '1.0.0', 'platform',
 '["detail_page","advanced_crud","header_line"]', '["field"]', true,
 '["section","grid_column","card","tab_panel"]', '[]',
 '{"properties":{"related_entity":{"type":"string"},"relationship_field":{"type":"string"},"display_fields":{"type":"array"},"max_items":{"type":"integer"},"allow_add":{"type":"boolean"},"allow_remove":{"type":"boolean"}}}',
 '{"max_items":10,"allow_add":true,"allow_remove":true}',
 '{"emits":["on_row_select","on_click"],"handles":["refresh"]}',
 '{"hidden_action":"remove_from_dom"}',
 'RelatedListRenderer', 'RelatedListPanel', true, '[]'),

('tree_view', 'Tree View', 'data', '1.0.0', 'platform',
 '["advanced_crud","detail_page","split_view"]', '["field"]', false,
 '["section","grid_column","card","tab_panel","split_pane"]', '[]',
 '{"properties":{"id_field":{"type":"string"},"parent_field":{"type":"string"},"label_field":{"type":"string"},"icon_field":{"type":"string"},"selectable":{"type":"boolean"},"expandable":{"type":"boolean"},"max_depth":{"type":"integer"}}}',
 '{"selectable":true,"expandable":true}',
 '{"emits":["on_row_select","on_click","on_change"],"handles":["refresh","expand_all","collapse_all"]}',
 '{"hidden_action":"remove_from_dom"}',
 'TreeViewRenderer', 'TreeViewPanel', true, '[]'),

('kanban_board', 'Kanban Board', 'data', '1.0.0', 'platform',
 '["kanban","dashboard"]', '["field"]', false,
 '["page_root","section","tab_panel"]', '[]',
 '{"properties":{"status_field":{"type":"string"},"columns":{"type":"array"},"card_title_field":{"type":"string"},"card_subtitle_field":{"type":"string"},"draggable":{"type":"boolean"},"swimlane_field":{"type":"string"}}}',
 '{"draggable":true}',
 '{"emits":["on_change","on_row_select","on_status_change"],"handles":["refresh"]}',
 '{"hidden_action":"remove_from_dom"}',
 'KanbanBoardRenderer', 'KanbanBoardPanel', true, '[]'),

('calendar_view', 'Calendar View', 'data', '1.0.0', 'platform',
 '["calendar","dashboard"]', '["field"]', false,
 '["page_root","section","tab_panel","grid_column"]', '[]',
 '{"properties":{"date_field":{"type":"string"},"end_date_field":{"type":"string"},"title_field":{"type":"string"},"default_view":{"type":"string","enum":["month","week","day"]},"color_field":{"type":"string"}}}',
 '{"default_view":"month"}',
 '{"emits":["on_click","on_change","on_row_select"],"handles":["refresh","goto_date"]}',
 '{"hidden_action":"remove_from_dom"}',
 'CalendarViewRenderer', 'CalendarViewPanel', true, '[]'),

('timeline', 'Timeline', 'data', '1.0.0', 'platform',
 '["detail_page","advanced_crud","dashboard"]', '["field"]', false,
 '["section","grid_column","card","tab_panel"]', '[]',
 '{"properties":{"date_field":{"type":"string"},"title_field":{"type":"string"},"description_field":{"type":"string"},"icon_field":{"type":"string"},"orientation":{"type":"string","enum":["vertical","horizontal"]},"max_items":{"type":"integer"}}}',
 '{"orientation":"vertical","max_items":20}',
 '{"emits":["on_click"],"handles":["refresh"]}',
 '{"hidden_action":"remove_from_dom"}',
 'TimelineRenderer', 'TimelinePanel', true, '[]'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- ACTION (5)
-- ═══════════════════════════════════════════════════════════════════════════════
('button', 'Button', 'action', '1.0.0', 'platform',
 '["all"]', '[]', false, '["section","grid_column","card","accordion","form_section","tab_panel","toolbar","modal_container","drawer_panel","empty_state"]', '["icon"]',
 '{"properties":{"label":{"type":"string"},"variant":{"type":"string","enum":["primary","secondary","ghost","danger","link"]},"size":{"type":"string","enum":["xs","sm","md","lg"]},"icon":{"type":"string"},"icon_position":{"type":"string","enum":["left","right"]},"loading":{"type":"boolean"},"full_width":{"type":"boolean"}}}',
 '{"variant":"primary","size":"md","icon_position":"left","loading":false,"full_width":false}',
 '{"emits":["on_click"],"handles":["disable","enable","show","hide","set_loading"]}',
 '{"hidden_action":"remove_from_dom"}',
 'ButtonRenderer', 'ButtonPanel', true, '[]'),

('icon_button', 'Icon Button', 'action', '1.0.0', 'platform',
 '["all"]', '[]', false, '["section","grid_column","card","accordion","form_section","tab_panel","toolbar","data_table"]', '[]',
 '{"properties":{"icon":{"type":"string"},"tooltip":{"type":"string"},"variant":{"type":"string","enum":["default","ghost","danger"]},"size":{"type":"string","enum":["xs","sm","md","lg"]}}}',
 '{"variant":"default","size":"md"}',
 '{"emits":["on_click"],"handles":["disable","enable","show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'IconButtonRenderer', 'IconButtonPanel', true, '[]'),

('link', 'Link', 'action', '1.0.0', 'platform',
 '["all"]', '["field","static"]', false, '["section","grid_column","card","accordion","form_section","tab_panel","toolbar","paragraph"]', '[]',
 '{"properties":{"text":{"type":"string"},"href":{"type":"string"},"target":{"type":"string","enum":["_self","_blank"]},"variant":{"type":"string","enum":["default","muted","primary"]}}}',
 '{"target":"_self","variant":"default"}',
 '{"emits":["on_click"],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'LinkRenderer', 'LinkPanel', true, '[]'),

('action_menu', 'Action Menu', 'action', '1.0.0', 'platform',
 '["all"]', '[]', false, '["section","grid_column","card","toolbar","data_table","tab_panel"]', '[]',
 '{"properties":{"trigger_label":{"type":"string"},"trigger_icon":{"type":"string"},"items":{"type":"array"},"placement":{"type":"string","enum":["bottom-start","bottom-end","top-start","top-end"]}}}',
 '{"trigger_icon":"more-vertical","placement":"bottom-end"}',
 '{"emits":["on_click"],"handles":["show","hide"]}',
 '{"hidden_action":"remove_from_dom"}',
 'ActionMenuRenderer', 'ActionMenuPanel', true, '[]'),

('toolbar', 'Toolbar', 'action', '1.0.0', 'platform',
 '["all"]', '[]', true, '["page_root","section","card","tab_panel","header_line_section"]', '["button","icon_button","link","action_menu","badge","search_bar"]',
 '{"properties":{"position":{"type":"string","enum":["top","bottom"]},"align":{"type":"string","enum":["left","center","right","space-between"]},"sticky":{"type":"boolean"}}}',
 '{"position":"top","align":"space-between","sticky":false}',
 '{"emits":[],"handles":["show","hide"]}',
 '{}', 'ToolbarRenderer', 'ToolbarPanel', true, '[]'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- NAVIGATION (4)
-- ═══════════════════════════════════════════════════════════════════════════════
('breadcrumb_nav', 'Breadcrumb Navigation', 'navigation', '1.0.0', 'platform',
 '["all"]', '[]', false, '["page_root","section"]', '[]',
 '{"properties":{"items":{"type":"array"},"separator":{"type":"string","enum":["/",">","·"]},"max_items":{"type":"integer"}}}',
 '{"separator":"/"}',
 '{"emits":["on_click"],"handles":[]}',
 '{}', 'BreadcrumbNavRenderer', 'BreadcrumbNavPanel', true, '[]'),

('tab_group', 'Tab Group', 'navigation', '1.0.0', 'platform',
 '["all"]', '[]', false, '["section","card","page_root","tab_panel"]', '[]',
 '{"properties":{"items":{"type":"array"},"variant":{"type":"string","enum":["default","pills","underline"]},"size":{"type":"string","enum":["sm","md","lg"]}}}',
 '{"variant":"default","size":"md"}',
 '{"emits":["on_change"],"handles":[]}',
 '{}', 'TabGroupRenderer', 'TabGroupPanel', true, '[]'),

('stepper', 'Stepper', 'navigation', '1.0.0', 'platform',
 '["wizard"]', '[]', false, '["page_root","section"]', '[]',
 '{"properties":{"steps":{"type":"array"},"orientation":{"type":"string","enum":["horizontal","vertical"]},"allow_click_navigation":{"type":"boolean"}}}',
 '{"orientation":"horizontal","allow_click_navigation":false}',
 '{"emits":["on_change"],"handles":["next","prev","goto"]}',
 '{}', 'StepperRenderer', 'StepperPanel', true, '[]'),

('pagination', 'Pagination', 'navigation', '1.0.0', 'platform',
 '["all"]', '[]', false, '["section","card","tab_panel","page_root"]', '[]',
 '{"properties":{"page_sizes":{"type":"array"},"default_page_size":{"type":"integer"},"show_total":{"type":"boolean"},"show_page_size_selector":{"type":"boolean"}}}',
 '{"page_sizes":[10,25,50,100],"default_page_size":25,"show_total":true,"show_page_size_selector":true}',
 '{"emits":["on_change"],"handles":[]}',
 '{}', 'PaginationRenderer', 'PaginationPanel', true, '[]'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- COMPOSITE (7)
-- ═══════════════════════════════════════════════════════════════════════════════
('header_line_section', 'Header-Line Section', 'composite', '1.0.0', 'platform',
 '["header_line"]', '[]', true, '["page_root"]', '["all"]',
 '{"properties":{"section_type":{"type":"string","enum":["header","line"]},"title":{"type":"string"},"show_toolbar":{"type":"boolean"}}}',
 '{"section_type":"header","show_toolbar":true}',
 '{"emits":[],"handles":["show","hide"]}',
 '{}', 'HeaderLineSectionRenderer', 'HeaderLineSectionPanel', true, '[]'),

('form_section', 'Form Section', 'composite', '1.0.0', 'platform',
 '["all"]', '[]', true, '["page_root","section","grid_column","card","tab_panel","wizard_step_container"]', '["all"]',
 '{"properties":{"title":{"type":"string"},"columns":{"type":"integer","minimum":1,"maximum":4},"mode":{"type":"string","enum":["view","edit","create"]},"show_divider":{"type":"boolean"}}}',
 '{"columns":2,"mode":"edit","show_divider":true}',
 '{"emits":["on_submit","on_validate"],"handles":["reset","validate","set_mode"]}',
 '{}', 'FormSectionRenderer', 'FormSectionPanel', true, '[]'),

('search_bar', 'Search Bar', 'composite', '1.0.0', 'platform',
 '["all"]', '[]', false, '["page_root","section","toolbar","card","tab_panel"]', '[]',
 '{"properties":{"placeholder":{"type":"string"},"debounce_ms":{"type":"integer"},"search_fields":{"type":"array"},"show_filter_toggle":{"type":"boolean"}}}',
 '{"placeholder":"Search...","debounce_ms":300,"show_filter_toggle":false}',
 '{"emits":["on_change","on_submit"],"handles":["clear","focus"]}',
 '{}', 'SearchBarRenderer', 'SearchBarPanel', true, '[]'),

('filter_panel', 'Filter Panel', 'composite', '1.0.0', 'platform',
 '["standard_crud","advanced_crud","header_line","dashboard"]', '[]', true, '["page_root","section","drawer_panel","card"]', '[]',
 '{"properties":{"filters":{"type":"array"},"layout":{"type":"string","enum":["inline","stacked","sidebar"]},"show_apply_button":{"type":"boolean"},"auto_apply":{"type":"boolean"}}}',
 '{"layout":"inline","show_apply_button":true,"auto_apply":false}',
 '{"emits":["on_change","on_submit"],"handles":["reset","apply"]}',
 '{}', 'FilterPanelRenderer', 'FilterPanelPanel', true, '[]'),

('detail_panel', 'Detail Panel', 'composite', '1.0.0', 'platform',
 '["detail_page","advanced_crud","split_view"]', '[]', true, '["page_root","section","split_pane","drawer_panel","tab_panel"]', '["all"]',
 '{"properties":{"title_field":{"type":"string"},"subtitle_field":{"type":"string"},"show_header":{"type":"boolean"},"show_actions":{"type":"boolean"}}}',
 '{"show_header":true,"show_actions":true}',
 '{"emits":["on_load"],"handles":["refresh","set_mode"]}',
 '{}', 'DetailPanelRenderer', 'DetailPanelPanel', true, '[]'),

('comment_thread', 'Comment Thread', 'composite', '1.0.0', 'platform',
 '["detail_page","advanced_crud"]', '["field"]', true, '["section","grid_column","card","tab_panel","drawer_panel"]', '[]',
 '{"properties":{"entity_field":{"type":"string"},"allow_replies":{"type":"boolean"},"allow_edit":{"type":"boolean"},"allow_delete":{"type":"boolean"},"max_depth":{"type":"integer"},"show_avatar":{"type":"boolean"}}}',
 '{"allow_replies":true,"allow_edit":true,"allow_delete":false,"max_depth":3,"show_avatar":true}',
 '{"emits":["on_submit","on_delete"],"handles":["refresh"]}',
 '{}', 'CommentThreadRenderer', 'CommentThreadPanel', true, '[]'),

('file_preview', 'File Preview', 'composite', '1.0.0', 'platform',
 '["detail_page","advanced_crud"]', '["field"]', false, '["section","grid_column","card","tab_panel","modal_container"]', '[]',
 '{"properties":{"supported_types":{"type":"array"},"show_download":{"type":"boolean"},"show_fullscreen":{"type":"boolean"},"max_height":{"type":"string"}}}',
 '{"supported_types":["pdf","image","text"],"show_download":true,"show_fullscreen":true,"max_height":"500px"}',
 '{"emits":["on_click"],"handles":["show","hide"]}',
 '{}', 'FilePreviewRenderer', 'FilePreviewPanel', true, '[]'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- CONTAINER (2)
-- ═══════════════════════════════════════════════════════════════════════════════
('repeater', 'Repeater', 'container', '1.0.0', 'platform',
 '["all"]', '["field"]', true, '["page_root","section","grid_column","card","tab_panel","form_section"]', '["all"]',
 '{"properties":{"source_field":{"type":"string"},"min_items":{"type":"integer"},"max_items":{"type":"integer"},"allow_add":{"type":"boolean"},"allow_remove":{"type":"boolean"},"allow_reorder":{"type":"boolean"}}}',
 '{"min_items":0,"allow_add":true,"allow_remove":true,"allow_reorder":true}',
 '{"emits":["on_change"],"handles":["add_item","remove_item","refresh"]}',
 '{"hidden_action":"remove_from_dom"}',
 'RepeaterRenderer', 'RepeaterPanel', true, '[]'),

('conditional_container', 'Conditional Container', 'container', '1.0.0', 'platform',
 '["all"]', '[]', true, '["page_root","section","grid_column","card","tab_panel","form_section"]', '["all"]',
 '{"properties":{"condition_type":{"type":"string","enum":["field_equals","expression","role_in"]},"field_key":{"type":"string"},"value":{},"expression":{"type":"string"},"roles":{"type":"array"},"else_visible":{"type":"boolean"}}}',
 '{"condition_type":"field_equals","else_visible":false}',
 '{"emits":[],"handles":[]}',
 '{"hidden_action":"remove_from_dom"}',
 'ConditionalContainerRenderer', 'ConditionalContainerPanel', true, '[]')

ON CONFLICT (component_code) DO UPDATE SET
  component_name = EXCLUDED.component_name,
  category = EXCLUDED.category,
  version = EXCLUDED.version,
  supported_surfaces = EXCLUDED.supported_surfaces,
  supported_bindings = EXCLUDED.supported_bindings,
  is_container = EXCLUDED.is_container,
  allowed_parents = EXCLUDED.allowed_parents,
  allowed_children = EXCLUDED.allowed_children,
  config_schema = EXCLUDED.config_schema,
  default_props = EXCLUDED.default_props,
  event_support = EXCLUDED.event_support,
  permission_behavior = EXCLUDED.permission_behavior,
  runtime_renderer = EXCLUDED.runtime_renderer,
  designer_panel = EXCLUDED.designer_panel,
  preview_support = EXCLUDED.preview_support,
  validation_rules = EXCLUDED.validation_rules;
