version: "3.9"
services:
  api:
    build:
      target: development
    volumes:
      - ./src/go:/app
    environment:
      LOG_LEVEL: debug
  studio:
    build:
      target: development
    volumes:
      - ./src/react:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    ports:
      - "3000:5173"
