export type TaskCategory =
  | 'Flow Control'
  | 'Parallel & Concurrency'
  | 'Human-in-Loop'
  | 'Records & Data'
  | 'Direct Database'
  | 'Business Rules'
  | 'Data Transformation'
  | 'Security & Compliance'
  | 'Integrations'
  | 'Platform & Orchestration'
  | 'AI & Automation'
  | 'Variables & State'

export interface TaskTypeConfig {
  type: string
  label: string
  category: TaskCategory
  description: string
  color: string
  bgColor: string
  isBranching: boolean
  defaultBranchLabels?: string[]
  iconName: string
  tier: 'standard' | 'advanced'
  whenToUse: string
  example: string
}

export const TASK_CATEGORIES: TaskCategory[] = [
  'Flow Control',
  'Parallel & Concurrency',
  'Human-in-Loop',
  'Records & Data',
  'Direct Database',
  'Business Rules',
  'Data Transformation',
  'Security & Compliance',
  'Integrations',
  'Platform & Orchestration',
  'AI & Automation',
  'Variables & State',
]

export const TASK_TYPE_REGISTRY: TaskTypeConfig[] = [
  // ── Flow Control ──────────────────────────────────────────────────────────
  {
    type: 'start',
    label: 'Start',
    category: 'Flow Control',
    description: 'Entry point of the workflow. Extracts request body, params and headers.',
    color: 'var(--brand-700, #1e3a8a)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Play',
    tier: 'standard',
    whenToUse: 'Always the first step. Extracts inputs from the request.',
    example: 'When your workflow is triggered by a POST request, the Start step makes the body fields available.',
  },
  {
    type: 'end',
    label: 'End',
    category: 'Flow Control',
    description: 'Terminates the workflow. Returns a response to the caller.',
    color: 'var(--brand-700, #1e3a8a)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Square',
    tier: 'standard',
    whenToUse: 'Always the last step. Sends the final response back to the caller.',
    example: 'After processing, the End step returns a 200 OK with the customer record.',
  },
  {
    type: 'Condition',
    label: 'Condition',
    category: 'Flow Control',
    description: 'Branches into "Yes" or "No" path based on one or more conditions.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['onSuccess', 'onFailure'],
    iconName: 'GitBranch',
    tier: 'standard',
    whenToUse: 'Use when you need a Yes/No decision at a specific point.',
    example: 'Check if order total > 1000 — Yes goes to Approval, No goes straight to Confirm.',
  },
  {
    type: 'Switch',
    label: 'Switch / Router',
    category: 'Flow Control',
    description: 'Routes to one of several paths based on a value. Like a traffic director.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['case1', 'default'],
    iconName: 'Shuffle',
    tier: 'standard',
    whenToUse: 'Use when you have 3 or more possible paths based on a value.',
    example: 'Route a request based on country: UK → VAT step, US → Tax step, Other → Default.',
  },
  {
    type: 'Loop',
    label: 'Loop',
    category: 'Flow Control',
    description: 'Repeats a set of steps while a condition is true.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['tasks'],
    iconName: 'RefreshCw',
    tier: 'standard',
    whenToUse: 'Repeat steps while a condition remains true.',
    example: 'Keep fetching the next page of records until there are no more pages.',
  },
  {
    type: 'Iterator',
    label: 'Iterator',
    category: 'Flow Control',
    description: 'Runs steps for each item in a list. Like "for each order, do this".',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['tasks'],
    iconName: 'List',
    tier: 'standard',
    whenToUse: 'Run the same steps for every item in a list.',
    example: 'For each line item in an invoice, calculate the VAT amount.',
  },
  {
    type: 'Transaction',
    label: 'Transaction',
    category: 'Flow Control',
    description: 'All-or-nothing block. If any step fails, the rollback steps run automatically.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['tasks', 'rollback'],
    iconName: 'ShieldCheck',
    tier: 'standard',
    whenToUse: 'All-or-nothing operation: if any step fails, rollback runs automatically.',
    example: 'Debit account A and credit account B — if the credit fails, the debit is reversed.',
  },

  // ── Parallel & Concurrency ────────────────────────────────────────────────
  {
    type: 'Parallel',
    label: 'Parallel',
    category: 'Parallel & Concurrency',
    description: 'Run multiple branches at the same time, then wait for all to finish.',
    color: 'var(--warning-500, #f59e0b)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['branch1', 'branch2'],
    iconName: 'Columns',
    tier: 'standard',
    whenToUse: 'Run multiple independent operations at the same time to save time.',
    example: 'Send an email and update a record at the same time instead of one after the other.',
  },
  {
    type: 'Promise',
    label: 'Promise',
    category: 'Parallel & Concurrency',
    description: 'Runs concurrent async steps and collects their results.',
    color: 'var(--warning-500, #f59e0b)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['tasks'],
    iconName: 'Zap',
    tier: 'advanced',
    whenToUse: 'Use when you need fine-grained control over concurrent async operations and their individual outcomes.',
    example: 'Run three external API calls simultaneously and collect all results before proceeding.',
  },

  // ── Human-in-Loop ─────────────────────────────────────────────────────────
  {
    type: 'Timer',
    label: 'Wait / Timer',
    category: 'Human-in-Loop',
    description: 'Pause the workflow for a set duration or until a specific date/time.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Clock',
    tier: 'standard',
    whenToUse: 'Pause the workflow for a set time before continuing.',
    example: 'Wait 24 hours after sending a quote before following up automatically.',
  },
  {
    type: 'Approval',
    label: 'Approval Gate',
    category: 'Human-in-Loop',
    description: 'Pause and send an approval request to a person or team. Resume when approved or rejected.',
    color: 'var(--success-600, #16a34a)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'UserCheck',
    tier: 'standard',
    whenToUse: 'Pause and ask a person to approve before continuing.',
    example: 'A finance manager must approve purchase requests over £5,000.',
  },

  // ── Records & Data ────────────────────────────────────────────────────────
  {
    type: 'Document',
    label: 'Document',
    category: 'Records & Data',
    description: 'Create, read, update or delete a single record in an entity.',
    color: 'var(--brand-500, #3b82f6)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'FileText',
    tier: 'standard',
    whenToUse: 'Read or write a single record in an entity (table).',
    example: 'Fetch the Customer record by the ID in the request, then use it in the next step.',
  },
  {
    type: 'Query',
    label: 'Query',
    category: 'Records & Data',
    description: 'Search and filter entity records. Supports paging and sorting.',
    color: 'var(--brand-500, #3b82f6)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Search',
    tier: 'standard',
    whenToUse: 'Search for multiple records matching criteria.',
    example: 'Find all open Orders for a given Customer, sorted by date.',
  },
  {
    type: 'Entity',
    label: 'Entity',
    category: 'Records & Data',
    description: 'Perform entity-level operations like clone, link, or bulk operations.',
    color: 'var(--brand-500, #3b82f6)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Database',
    tier: 'standard',
    whenToUse: 'Perform entity-level operations beyond single-record CRUD, such as bulk actions or linking records.',
    example: 'Clone all line items from a template order into a new order.',
  },
  {
    type: 'Identifier',
    label: 'Identifier',
    category: 'Records & Data',
    description: 'Look up a record by ID with type-safe coercion and null handling.',
    color: 'var(--brand-500, #3b82f6)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Hash',
    tier: 'advanced',
    whenToUse: 'Use when you need type-safe ID resolution with explicit null handling in complex data pipelines.',
    example: 'Coerce a string ID from a webhook payload to a validated UUID before querying the database.',
  },
  {
    type: 'History',
    label: 'History',
    category: 'Records & Data',
    description: 'Fetch the change history or audit trail for a record.',
    color: 'var(--brand-500, #3b82f6)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Clock3',
    tier: 'advanced',
    whenToUse: 'Use when you need to inspect the change log or audit trail of a specific record.',
    example: 'Retrieve the last 5 changes to a contract record to show in a timeline view.',
  },
  {
    type: 'Version',
    label: 'Version',
    category: 'Records & Data',
    description: 'Read or compare artifact/document versions.',
    color: 'var(--brand-500, #3b82f6)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'GitCommit',
    tier: 'advanced',
    whenToUse: 'Use when you need to compare or retrieve a specific published version of an artifact.',
    example: 'Load version 3 of a contract template to compare it against the current draft.',
  },

  // ── Direct Database ───────────────────────────────────────────────────────
  {
    type: 'Repository',
    label: 'Repository',
    category: 'Direct Database',
    description: 'Abstract data store operations (find, save, remove) via the repository pattern.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Server',
    tier: 'advanced',
    whenToUse: 'Use when you need low-level repository pattern operations not covered by the Document or Query tasks.',
    example: 'Call a custom repository method that handles complex upsert logic for a third-party sync.',
  },
  {
    type: 'ORM',
    label: 'ORM',
    category: 'Direct Database',
    description: 'Execute a raw SQL query with bound parameters.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Table',
    tier: 'advanced',
    whenToUse: 'Use when you need to execute raw SQL that cannot be expressed through the standard Query task.',
    example: 'Run a complex multi-table SQL aggregation that the Query task cannot express.',
  },
  {
    type: 'Trino',
    label: 'Trino / Analytics',
    category: 'Direct Database',
    description: 'Run an analytics SQL query on the Trino / Presto cluster.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'BarChart3',
    tier: 'advanced',
    whenToUse: 'Use when you need to run large-scale analytical queries across the data warehouse.',
    example: 'Run a monthly revenue aggregation across all tenants using the Trino analytics cluster.',
  },

  // ── Business Rules ────────────────────────────────────────────────────────
  {
    type: 'Rule',
    label: 'Rule',
    category: 'Business Rules',
    description: 'Evaluate a rule set. Rules can block the request, warn, or set field values.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: false,
    iconName: 'Shield',
    tier: 'standard',
    whenToUse: 'Apply a set of business rules and decide whether to block, warn, or continue.',
    example: 'Block a withdrawal if the account balance would drop below zero.',
  },
  {
    type: 'Resolver',
    label: 'Resolver',
    category: 'Business Rules',
    description: 'Evaluate a JSONata expression to compute a new value from existing data.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: false,
    iconName: 'Code2',
    tier: 'standard',
    whenToUse: 'Compute a new value from a JSONata expression using data from previous steps.',
    example: "Calculate the total: quantity × unit price, and store it as 'orderTotal'.",
  },
  {
    type: 'Validator',
    label: 'Validator',
    category: 'Business Rules',
    description: 'Validate input data against a schema or set of rules. Stop if invalid.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: false,
    iconName: 'CheckCircle',
    tier: 'standard',
    whenToUse: 'Check that input data meets required standards before processing.',
    example: 'Ensure the email field is a valid email address before saving the record.',
  },
  {
    type: 'Filter',
    label: 'Filter',
    category: 'Business Rules',
    description: 'Filter an array of items using a condition. Returns only matching items.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: false,
    iconName: 'Filter',
    tier: 'standard',
    whenToUse: "Remove items from a list that don't match a condition.",
    example: 'From a list of invoices, keep only the ones that are overdue.',
  },
  {
    type: 'Schema',
    label: 'Schema',
    category: 'Business Rules',
    description: 'Validate data against a JSON Schema definition.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: false,
    iconName: 'Layout',
    tier: 'advanced',
    whenToUse: 'Use when you need strict JSON Schema validation beyond what the Validator task provides.',
    example: 'Validate an incoming webhook payload against a published JSON Schema before processing.',
  },

  // ── Data Transformation ───────────────────────────────────────────────────
  {
    type: 'Date',
    label: 'Date',
    category: 'Data Transformation',
    description: 'Format, parse, compare or do arithmetic on dates and times.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Calendar',
    tier: 'standard',
    whenToUse: 'Perform date calculations or format dates.',
    example: 'Calculate the due date as 30 days after the invoice creation date.',
  },
  {
    type: 'UUID',
    label: 'UUID',
    category: 'Data Transformation',
    description: 'Generate a unique ID (v4 or v7). Useful for creating record identifiers.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Fingerprint',
    tier: 'standard',
    whenToUse: 'Generate a unique ID for a new record.',
    example: 'Create a unique reference number for each support ticket.',
  },
  {
    type: 'JSON',
    label: 'JSON',
    category: 'Data Transformation',
    description: 'Parse, stringify, merge or pick fields from a JSON object.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Braces',
    tier: 'standard',
    whenToUse: 'Parse, build, or manipulate JSON data.',
    example: 'Extract specific fields from a complex API response.',
  },
  {
    type: 'Object',
    label: 'Object',
    category: 'Data Transformation',
    description: 'Build or transform an object — pick fields, rename keys, set defaults.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Box',
    tier: 'standard',
    whenToUse: 'Build or combine data objects.',
    example: 'Merge customer details and order details into a single object for the email template.',
  },
  {
    type: 'Array',
    label: 'Array',
    category: 'Data Transformation',
    description: 'Map, reduce, sort, group or merge an array of items.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'List',
    tier: 'standard',
    whenToUse: 'Sort, group, or transform a list of items.',
    example: 'Sort a list of products by price before returning them in the response.',
  },
  {
    type: 'String',
    label: 'String',
    category: 'Data Transformation',
    description: 'Manipulate text — trim, split, replace, pad, format or apply regex.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Type',
    tier: 'standard',
    whenToUse: 'Manipulate text values.',
    example: 'Format a phone number, extract a domain from an email, or join name fields.',
  },
  {
    type: 'Math',
    label: 'Math',
    category: 'Data Transformation',
    description: 'Perform arithmetic or statistical calculations.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Calculator',
    tier: 'standard',
    whenToUse: 'Perform numeric calculations.',
    example: 'Calculate 20% VAT on the order total.',
  },

  // ── Security & Compliance ─────────────────────────────────────────────────
  {
    type: 'Geometry',
    label: 'Geometry',
    category: 'Security & Compliance',
    description: 'Geospatial operations — distance, within polygon, GeoJSON.',
    color: 'var(--color-text-muted, #9ca3af)',
    bgColor: 'var(--color-surface-1, #f3f4f6)',
    isBranching: false,
    iconName: 'MapPin',
    tier: 'advanced',
    whenToUse: 'Use when you need geospatial calculations such as proximity checks or polygon containment.',
    example: 'Check whether a delivery address falls within a permitted service area polygon.',
  },
  {
    type: 'Security',
    label: 'Security',
    category: 'Security & Compliance',
    description: 'Assert permissions, check roles, or verify resource ownership.',
    color: 'var(--error-600, #dc2626)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Lock',
    tier: 'standard',
    whenToUse: 'Assert that the current user has the required permission before proceeding.',
    example: 'Verify the acting user has the "finance.write" role before allowing a payment to be submitted.',
  },
  {
    type: 'Crypto',
    label: 'Crypto',
    category: 'Security & Compliance',
    description: 'Encrypt, decrypt, or hash data using AES or bcrypt.',
    color: 'var(--error-600, #dc2626)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Key',
    tier: 'advanced',
    whenToUse: 'Use when you need to encrypt, decrypt, or hash sensitive values at the workflow level.',
    example: 'Hash a user-supplied PIN with bcrypt before storing it in the record.',
  },
  {
    type: 'RSA',
    label: 'RSA',
    category: 'Security & Compliance',
    description: 'RSA digital signature — sign or verify data.',
    color: 'var(--error-600, #dc2626)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'KeyRound',
    tier: 'advanced',
    whenToUse: 'Use when you need to produce or verify an RSA digital signature on a payload.',
    example: 'Sign a contract PDF digest with the organisation RSA private key before sending to a third party.',
  },

  // ── Integrations ───────────────────────────────────────────────────────────
  {
    type: 'HTTP',
    label: 'HTTP Request',
    category: 'Integrations',
    description: 'Call an external REST API or web service.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Globe',
    tier: 'standard',
    whenToUse: 'Call any external REST API and use its response.',
    example: "POST to Stripe's payment API with the order amount and get back a payment result.",
  },
  {
    type: 'SMTP',
    label: 'Send Email',
    category: 'Integrations',
    description: 'Send an email via SMTP. Supports templates and attachments.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Mail',
    tier: 'standard',
    whenToUse: 'Send an email from the workflow.',
    example: 'Send an order confirmation email to the customer after a successful purchase.',
  },
  {
    type: 'SMS',
    label: 'Send SMS',
    category: 'Integrations',
    description: 'Send an SMS message to a phone number.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'MessageSquare',
    tier: 'standard',
    whenToUse: 'Send a text message.',
    example: 'Send a delivery notification SMS when an order status changes to Shipped.',
  },
  {
    type: 'Notification',
    label: 'Notification',
    category: 'Integrations',
    description: 'Send a push notification or WebSocket event to a user or device.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Bell',
    tier: 'standard',
    whenToUse: 'Send a push or in-app notification.',
    example: 'Alert the assigned agent when a new support ticket is created.',
  },
  {
    type: 'Webhook',
    label: 'Webhook',
    category: 'Integrations',
    description: 'Send an HTTP POST to a registered webhook URL.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Webhook',
    tier: 'standard',
    whenToUse: 'Call an external URL with data when something happens.',
    example: 'Notify your CRM system when a new lead is created in Excellon.',
  },
  {
    type: 'Queue',
    label: 'Message Queue',
    category: 'Integrations',
    description: 'Publish a message to Kafka, RabbitMQ or SQS.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Radio',
    tier: 'standard',
    whenToUse: 'Send a message to a queue for async processing.',
    example: 'Place an order processing job on the queue so it runs in the background.',
  },
  {
    type: 'MinIO',
    label: 'File Storage',
    category: 'Integrations',
    description: 'Upload, download or delete files from MinIO / S3-compatible storage.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'HardDrive',
    tier: 'advanced',
    whenToUse: 'Use when you need to read or write files in object storage as part of a workflow.',
    example: 'Upload a generated PDF report to MinIO and return the download URL.',
  },
  {
    type: 'Azure',
    label: 'Azure',
    category: 'Integrations',
    description: 'Interact with Azure Blob, Service Bus or Azure Functions.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Cloud',
    tier: 'advanced',
    whenToUse: 'Use when you need to interact with Azure-specific services such as Blob, Service Bus, or Functions.',
    example: 'Send a message to an Azure Service Bus topic for downstream processing by a .NET service.',
  },
  {
    type: 'ESQuery',
    label: 'Search (Elasticsearch)',
    category: 'Integrations',
    description: 'Run a full-text or structured query against Elasticsearch.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'SearchCode',
    tier: 'advanced',
    whenToUse: 'Use when you need full-text or complex structured search backed by Elasticsearch.',
    example: 'Search the product catalogue by keyword and return ranked results from Elasticsearch.',
  },

  // ── Platform & Orchestration ──────────────────────────────────────────────
  {
    type: 'Action',
    label: 'Call Action',
    category: 'Platform & Orchestration',
    description: 'Invoke another workflow action in this project as a sub-step.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Play',
    tier: 'standard',
    whenToUse: 'Run another workflow action from within this workflow.',
    example: "Call the 'Calculate Discount' action with the order data and use its result here.",
  },
  {
    type: 'Workflow',
    label: 'Sub-Workflow',
    category: 'Platform & Orchestration',
    description: 'Invoke a saved workflow as a reusable sub-process.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'GitMerge',
    tier: 'standard',
    whenToUse: 'Run another workflow as a sub-task.',
    example: "Trigger the 'Onboarding Workflow' as part of a larger Customer Registration workflow.",
  },
  {
    type: 'Subscription',
    label: 'Subscription',
    category: 'Platform & Orchestration',
    description: 'Manage pub/sub event subscriptions.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Rss',
    tier: 'advanced',
    whenToUse: 'Use when you need to subscribe or unsubscribe from platform events programmatically.',
    example: 'Subscribe to inventory update events so downstream workflows fire automatically when stock changes.',
  },
  {
    type: 'Cache',
    label: 'Cache',
    category: 'Platform & Orchestration',
    description: 'Read, write or invalidate a value in the Redis cache.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Layers',
    tier: 'standard',
    whenToUse: "Save a result so the workflow doesn't fetch it repeatedly.",
    example: 'Cache the product catalogue for 5 minutes to speed up high-traffic workflows.',
  },
  {
    type: 'Export',
    label: 'Export',
    category: 'Platform & Orchestration',
    description: 'Export data to CSV, Excel or PDF format.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Download',
    tier: 'standard',
    whenToUse: 'Export data to a downloadable file.',
    example: "Export all this month's invoices to an Excel file for the finance team.",
  },
  {
    type: 'Template',
    label: 'Template',
    category: 'Platform & Orchestration',
    description: 'Render a Handlebars or Mustache template with data.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'FileCode',
    tier: 'standard',
    whenToUse: 'Fill a document template with data from the workflow.',
    example: 'Generate a PDF contract using the customer name and order details.',
  },
  {
    type: 'UIComponent',
    label: 'UI Component',
    category: 'Platform & Orchestration',
    description: 'Dynamically update or trigger a UI component.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'LayoutTemplate',
    tier: 'advanced',
    whenToUse: 'Use when you need server-side logic to directly update or control a frontend UI component.',
    example: 'Push a live status update to a dashboard widget when a long-running process completes.',
  },

  // ── AI & Automation ───────────────────────────────────────────────────────
  {
    type: 'AI',
    label: 'AI / LLM',
    category: 'AI & Automation',
    description: 'Send a prompt to an AI language model and get structured output back.',
    color: 'var(--success-600, #16a34a)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'Cpu',
    tier: 'standard',
    whenToUse: 'Use an AI model to analyse, generate, or classify content.',
    example: 'Send customer feedback text to Claude and get back a sentiment score and summary.',
  },
  {
    type: 'Keycloak',
    label: 'Keycloak',
    category: 'AI & Automation',
    description: 'Identity provider operations — introspect token, assign or revoke role.',
    color: 'var(--success-600, #16a34a)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'UserCog',
    tier: 'advanced',
    whenToUse: 'Use when you need to manage Keycloak identity operations such as role assignment or token introspection.',
    example: 'Assign the "approver" role in Keycloak to a user after they complete an onboarding step.',
  },
  {
    type: 'Provider',
    label: 'Provider',
    category: 'AI & Automation',
    description: 'Integrate with an external service provider.',
    color: 'var(--success-600, #16a34a)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'Plug',
    tier: 'advanced',
    whenToUse: 'Use when connecting to a pre-configured external service provider integration.',
    example: 'Call a configured Salesforce provider to sync a contact record from Excellon.',
  },

  // ── Variables & State ─────────────────────────────────────────────────────
  {
    type: 'Request',
    label: 'Request',
    category: 'Variables & State',
    description: 'Extract and bind fields from the incoming request body, query or headers.',
    color: 'var(--success-500, #22c55e)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'ArrowDownToLine',
    tier: 'standard',
    whenToUse: 'Extract and name specific fields from the incoming request.',
    example: 'Pull customerId from the URL params and body fields for use in downstream steps.',
  },
  {
    type: 'Response',
    label: 'Response',
    category: 'Variables & State',
    description: 'Build and return the HTTP response with a status code and payload.',
    color: 'var(--success-500, #22c55e)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'ArrowUpFromLine',
    tier: 'standard',
    whenToUse: 'Send the HTTP response back to whoever called this workflow.',
    example: 'Return the customer record with a 200 OK status code.',
  },
  {
    type: 'Variable',
    label: 'Variable',
    category: 'Variables & State',
    description: 'Declare or update a variable that you can reference throughout the workflow.',
    color: 'var(--success-500, #22c55e)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'Tag',
    tier: 'standard',
    whenToUse: 'Store a value in a named variable for use later in the workflow.',
    example: "Store the current date as 'today' at the start, then use it in multiple later steps.",
  },
  {
    type: 'Sequence',
    label: 'Sequence',
    category: 'Variables & State',
    description: 'Group a set of steps into a named sequence with break/continue control.',
    color: 'var(--success-500, #22c55e)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: true,
    defaultBranchLabels: ['tasks'],
    iconName: 'AlignLeft',
    tier: 'advanced',
    whenToUse: 'Use when you need to group steps with named break/continue control flow within a larger workflow.',
    example: 'Wrap a set of retry steps in a named sequence so you can break out of it cleanly on success.',
  },
  {
    type: 'State',
    label: 'State',
    category: 'Variables & State',
    description: 'Read or write to the workflow state bag — a shared scratch space.',
    color: 'var(--success-500, #22c55e)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: true,
    defaultBranchLabels: ['tasks'],
    iconName: 'Archive',
    tier: 'advanced',
    whenToUse: 'Use when you need a shared scratch space across branches or parallel steps in a complex workflow.',
    example: 'Write a running total to the state bag inside a loop and read it back after the loop ends.',
  },
]

export const TASK_REGISTRY_BY_TYPE = new Map<string, TaskTypeConfig>(
  TASK_TYPE_REGISTRY.map(t => [t.type, t])
)

export function getTaskConfig(type: string): TaskTypeConfig | undefined {
  return TASK_REGISTRY_BY_TYPE.get(type)
}
