export type TaskCategory =
  | 'Control Flow'
  | 'Parallel Execution'
  | 'Wait & Approval'
  | 'Data Access'
  | 'Repository & ORM'
  | 'Logic & Validation'
  | 'Transform'
  | 'Geo & Security'
  | 'Integration'
  | 'Platform'
  | 'AI & Identity'
  | 'State & Utility'

export interface TaskTypeConfig {
  type: string
  label: string
  category: TaskCategory
  description: string
  color: string
  bgColor: string
  isBranching: boolean
  defaultBranchLabels?: string[]
  iconName: string
}

export const TASK_CATEGORIES: TaskCategory[] = [
  'Control Flow',
  'Parallel Execution',
  'Wait & Approval',
  'Data Access',
  'Repository & ORM',
  'Logic & Validation',
  'Transform',
  'Geo & Security',
  'Integration',
  'Platform',
  'AI & Identity',
  'State & Utility',
]

export const TASK_TYPE_REGISTRY: TaskTypeConfig[] = [
  // ── Control Flow ──────────────────────────────────────────────────────────
  {
    type: 'start',
    label: 'Start',
    category: 'Control Flow',
    description: 'Entry point of the workflow. Extracts request body, params and headers.',
    color: 'var(--brand-700, #1e3a8a)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Play',
  },
  {
    type: 'end',
    label: 'End',
    category: 'Control Flow',
    description: 'Terminates the workflow. Returns a response to the caller.',
    color: 'var(--brand-700, #1e3a8a)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Square',
  },
  {
    type: 'Condition',
    label: 'Condition',
    category: 'Control Flow',
    description: 'Branches into "Yes" or "No" path based on one or more conditions.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['onSuccess', 'onFailure'],
    iconName: 'GitBranch',
  },
  {
    type: 'Switch',
    label: 'Switch / Router',
    category: 'Control Flow',
    description: 'Routes to one of several paths based on a value. Like a traffic director.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['case1', 'default'],
    iconName: 'Shuffle',
  },
  {
    type: 'Loop',
    label: 'Loop',
    category: 'Control Flow',
    description: 'Repeats a set of steps while a condition is true.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['tasks'],
    iconName: 'RefreshCw',
  },
  {
    type: 'Iterator',
    label: 'Iterator',
    category: 'Control Flow',
    description: 'Runs steps for each item in a list. Like "for each order, do this".',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['tasks'],
    iconName: 'List',
  },
  {
    type: 'Transaction',
    label: 'Transaction',
    category: 'Control Flow',
    description: 'All-or-nothing block. If any step fails, the rollback steps run automatically.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['tasks', 'rollback'],
    iconName: 'ShieldCheck',
  },

  // ── Parallel Execution ────────────────────────────────────────────────────
  {
    type: 'Parallel',
    label: 'Parallel',
    category: 'Parallel Execution',
    description: 'Run multiple branches at the same time, then wait for all to finish.',
    color: 'var(--warning-500, #f59e0b)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['branch1', 'branch2'],
    iconName: 'Columns',
  },
  {
    type: 'Promise',
    label: 'Promise',
    category: 'Parallel Execution',
    description: 'Runs concurrent async steps and collects their results.',
    color: 'var(--warning-500, #f59e0b)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: true,
    defaultBranchLabels: ['tasks'],
    iconName: 'Zap',
  },

  // ── Wait & Approval ───────────────────────────────────────────────────────
  {
    type: 'Timer',
    label: 'Wait / Timer',
    category: 'Wait & Approval',
    description: 'Pause the workflow for a set duration or until a specific date/time.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Clock',
  },
  {
    type: 'Approval',
    label: 'Approval Gate',
    category: 'Wait & Approval',
    description: 'Pause and send an approval request to a person or team. Resume when approved or rejected.',
    color: 'var(--success-600, #16a34a)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'UserCheck',
  },

  // ── Data Access ───────────────────────────────────────────────────────────
  {
    type: 'Document',
    label: 'Document',
    category: 'Data Access',
    description: 'Create, read, update or delete a single record in an entity.',
    color: 'var(--brand-500, #3b82f6)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'FileText',
  },
  {
    type: 'Query',
    label: 'Query',
    category: 'Data Access',
    description: 'Search and filter entity records. Supports paging and sorting.',
    color: 'var(--brand-500, #3b82f6)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Search',
  },
  {
    type: 'Entity',
    label: 'Entity',
    category: 'Data Access',
    description: 'Perform entity-level operations like clone, link, or bulk operations.',
    color: 'var(--brand-500, #3b82f6)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Database',
  },
  {
    type: 'Identifier',
    label: 'Identifier',
    category: 'Data Access',
    description: 'Look up a record by ID with type-safe coercion and null handling.',
    color: 'var(--brand-500, #3b82f6)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Hash',
  },
  {
    type: 'History',
    label: 'History',
    category: 'Data Access',
    description: 'Fetch the change history or audit trail for a record.',
    color: 'var(--brand-500, #3b82f6)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Clock3',
  },
  {
    type: 'Version',
    label: 'Version',
    category: 'Data Access',
    description: 'Read or compare artifact/document versions.',
    color: 'var(--brand-500, #3b82f6)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'GitCommit',
  },

  // ── Repository & ORM ──────────────────────────────────────────────────────
  {
    type: 'Repository',
    label: 'Repository',
    category: 'Repository & ORM',
    description: 'Abstract data store operations (find, save, remove) via the repository pattern.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Server',
  },
  {
    type: 'ORM',
    label: 'ORM',
    category: 'Repository & ORM',
    description: 'Execute a raw SQL query with bound parameters.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Table',
  },
  {
    type: 'Trino',
    label: 'Trino / Analytics',
    category: 'Repository & ORM',
    description: 'Run an analytics SQL query on the Trino / Presto cluster.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'BarChart3',
  },

  // ── Logic & Validation ────────────────────────────────────────────────────
  {
    type: 'Rule',
    label: 'Rule',
    category: 'Logic & Validation',
    description: 'Evaluate a rule set. Rules can block the request, warn, or set field values.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: false,
    iconName: 'Shield',
  },
  {
    type: 'Resolver',
    label: 'Resolver',
    category: 'Logic & Validation',
    description: 'Evaluate a JSONata expression to compute a new value from existing data.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: false,
    iconName: 'Code2',
  },
  {
    type: 'Validator',
    label: 'Validator',
    category: 'Logic & Validation',
    description: 'Validate input data against a schema or set of rules. Stop if invalid.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: false,
    iconName: 'CheckCircle',
  },
  {
    type: 'Filter',
    label: 'Filter',
    category: 'Logic & Validation',
    description: 'Filter an array of items using a condition. Returns only matching items.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: false,
    iconName: 'Filter',
  },
  {
    type: 'Schema',
    label: 'Schema',
    category: 'Logic & Validation',
    description: 'Validate data against a JSON Schema definition.',
    color: 'var(--warning-600, #d97706)',
    bgColor: 'var(--warning-50, #fffbeb)',
    isBranching: false,
    iconName: 'Layout',
  },

  // ── Transform ─────────────────────────────────────────────────────────────
  {
    type: 'Date',
    label: 'Date',
    category: 'Transform',
    description: 'Format, parse, compare or do arithmetic on dates and times.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Calendar',
  },
  {
    type: 'UUID',
    label: 'UUID',
    category: 'Transform',
    description: 'Generate a unique ID (v4 or v7). Useful for creating record identifiers.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Fingerprint',
  },
  {
    type: 'JSON',
    label: 'JSON',
    category: 'Transform',
    description: 'Parse, stringify, merge or pick fields from a JSON object.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Braces',
  },
  {
    type: 'Object',
    label: 'Object',
    category: 'Transform',
    description: 'Build or transform an object — pick fields, rename keys, set defaults.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Box',
  },
  {
    type: 'Array',
    label: 'Array',
    category: 'Transform',
    description: 'Map, reduce, sort, group or merge an array of items.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'List',
  },
  {
    type: 'String',
    label: 'String',
    category: 'Transform',
    description: 'Manipulate text — trim, split, replace, pad, format or apply regex.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Type',
  },
  {
    type: 'Math',
    label: 'Math',
    category: 'Transform',
    description: 'Perform arithmetic or statistical calculations.',
    color: 'var(--color-text-secondary, #6b7280)',
    bgColor: 'var(--color-surface-2, #f9fafb)',
    isBranching: false,
    iconName: 'Calculator',
  },

  // ── Geo & Security ────────────────────────────────────────────────────────
  {
    type: 'Geometry',
    label: 'Geometry',
    category: 'Geo & Security',
    description: 'Geospatial operations — distance, within polygon, GeoJSON.',
    color: 'var(--color-text-muted, #9ca3af)',
    bgColor: 'var(--color-surface-1, #f3f4f6)',
    isBranching: false,
    iconName: 'MapPin',
  },
  {
    type: 'Security',
    label: 'Security',
    category: 'Geo & Security',
    description: 'Assert permissions, check roles, or verify resource ownership.',
    color: 'var(--error-600, #dc2626)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Lock',
  },
  {
    type: 'Crypto',
    label: 'Crypto',
    category: 'Geo & Security',
    description: 'Encrypt, decrypt, or hash data using AES or bcrypt.',
    color: 'var(--error-600, #dc2626)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Key',
  },
  {
    type: 'RSA',
    label: 'RSA',
    category: 'Geo & Security',
    description: 'RSA digital signature — sign or verify data.',
    color: 'var(--error-600, #dc2626)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'KeyRound',
  },

  // ── Integration ───────────────────────────────────────────────────────────
  {
    type: 'HTTP',
    label: 'HTTP Request',
    category: 'Integration',
    description: 'Call an external REST API or web service.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Globe',
  },
  {
    type: 'SMTP',
    label: 'Send Email',
    category: 'Integration',
    description: 'Send an email via SMTP. Supports templates and attachments.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Mail',
  },
  {
    type: 'SMS',
    label: 'Send SMS',
    category: 'Integration',
    description: 'Send an SMS message to a phone number.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'MessageSquare',
  },
  {
    type: 'Notification',
    label: 'Notification',
    category: 'Integration',
    description: 'Send a push notification or WebSocket event to a user or device.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Bell',
  },
  {
    type: 'Webhook',
    label: 'Webhook',
    category: 'Integration',
    description: 'Send an HTTP POST to a registered webhook URL.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Webhook',
  },
  {
    type: 'Queue',
    label: 'Message Queue',
    category: 'Integration',
    description: 'Publish a message to Kafka, RabbitMQ or SQS.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Radio',
  },
  {
    type: 'MinIO',
    label: 'File Storage',
    category: 'Integration',
    description: 'Upload, download or delete files from MinIO / S3-compatible storage.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'HardDrive',
  },
  {
    type: 'Azure',
    label: 'Azure',
    category: 'Integration',
    description: 'Interact with Azure Blob, Service Bus or Azure Functions.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'Cloud',
  },
  {
    type: 'ESQuery',
    label: 'Search (Elasticsearch)',
    category: 'Integration',
    description: 'Run a full-text or structured query against Elasticsearch.',
    color: 'var(--error-500, #ef4444)',
    bgColor: 'var(--error-50, #fef2f2)',
    isBranching: false,
    iconName: 'SearchCode',
  },

  // ── Platform ──────────────────────────────────────────────────────────────
  {
    type: 'Action',
    label: 'Call Action',
    category: 'Platform',
    description: 'Invoke another workflow action in this project as a sub-step.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Play',
  },
  {
    type: 'Workflow',
    label: 'Sub-Workflow',
    category: 'Platform',
    description: 'Invoke a saved workflow as a reusable sub-process.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'GitMerge',
  },
  {
    type: 'Subscription',
    label: 'Subscription',
    category: 'Platform',
    description: 'Manage pub/sub event subscriptions.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Rss',
  },
  {
    type: 'Cache',
    label: 'Cache',
    category: 'Platform',
    description: 'Read, write or invalidate a value in the Redis cache.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Layers',
  },
  {
    type: 'Export',
    label: 'Export',
    category: 'Platform',
    description: 'Export data to CSV, Excel or PDF format.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'Download',
  },
  {
    type: 'Template',
    label: 'Template',
    category: 'Platform',
    description: 'Render a Handlebars or Mustache template with data.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'FileCode',
  },
  {
    type: 'UIComponent',
    label: 'UI Component',
    category: 'Platform',
    description: 'Dynamically update or trigger a UI component.',
    color: 'var(--brand-600, #2563eb)',
    bgColor: 'var(--brand-50, #eff6ff)',
    isBranching: false,
    iconName: 'LayoutTemplate',
  },

  // ── AI & Identity ─────────────────────────────────────────────────────────
  {
    type: 'AI',
    label: 'AI / LLM',
    category: 'AI & Identity',
    description: 'Send a prompt to an AI language model and get structured output back.',
    color: 'var(--success-600, #16a34a)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'Cpu',
  },
  {
    type: 'Keycloak',
    label: 'Keycloak',
    category: 'AI & Identity',
    description: 'Identity provider operations — introspect token, assign or revoke role.',
    color: 'var(--success-600, #16a34a)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'UserCog',
  },
  {
    type: 'Provider',
    label: 'Provider',
    category: 'AI & Identity',
    description: 'Integrate with an external service provider.',
    color: 'var(--success-600, #16a34a)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'Plug',
  },

  // ── State & Utility ───────────────────────────────────────────────────────
  {
    type: 'Request',
    label: 'Request',
    category: 'State & Utility',
    description: 'Extract and bind fields from the incoming request body, query or headers.',
    color: 'var(--success-500, #22c55e)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'ArrowDownToLine',
  },
  {
    type: 'Response',
    label: 'Response',
    category: 'State & Utility',
    description: 'Build and return the HTTP response with a status code and payload.',
    color: 'var(--success-500, #22c55e)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'ArrowUpFromLine',
  },
  {
    type: 'Variable',
    label: 'Variable',
    category: 'State & Utility',
    description: 'Declare or update a variable that you can reference throughout the workflow.',
    color: 'var(--success-500, #22c55e)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: false,
    iconName: 'Tag',
  },
  {
    type: 'Sequence',
    label: 'Sequence',
    category: 'State & Utility',
    description: 'Group a set of steps into a named sequence with break/continue control.',
    color: 'var(--success-500, #22c55e)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: true,
    defaultBranchLabels: ['tasks'],
    iconName: 'AlignLeft',
  },
  {
    type: 'State',
    label: 'State',
    category: 'State & Utility',
    description: 'Read or write to the workflow state bag — a shared scratch space.',
    color: 'var(--success-500, #22c55e)',
    bgColor: 'var(--success-50, #f0fdf4)',
    isBranching: true,
    defaultBranchLabels: ['tasks'],
    iconName: 'Archive',
  },
]

export const TASK_REGISTRY_BY_TYPE = new Map<string, TaskTypeConfig>(
  TASK_TYPE_REGISTRY.map(t => [t.type, t])
)

export function getTaskConfig(type: string): TaskTypeConfig | undefined {
  return TASK_REGISTRY_BY_TYPE.get(type)
}
