/**
 * Task Traversal Utilities for nth-level nested task operations
 * 
 * This module provides robust utilities for traversing, finding, updating, and deleting
 * tasks at any nesting level within a workflow definition. It supports all branching
 * task types: Condition, Switch, Iterator, Loop, Transaction, Promise, State.
 * 
 * Task Identification Strategy:
 * - Each task has a unique AI identifier (task._id) generated by Uid.next()
 * - The workflow engine uses task.id which should NOT be used for AI operations
 * - Tasks can also be identified by path: "parent_id.branchName.child_id"
 * - The path provides context about where a task is located in the hierarchy
 */

import { Step, Branches } from "../../../designer";

/**
 * Result of a task search operation
 */
export interface TaskSearchResult {
    task: Step | null;
    path: string[];        // Array of path segments: [parentId, branchName, taskId, ...]
    pathString: string;    // Dot-separated path string
    parent: Step | null;   // Parent branching task (if nested)
    branchName: string | null; // Name of branch containing this task
    depth: number;         // Nesting depth (0 = root level)
}

/**
 * Task info for listing
 */
export interface TaskInfo {
    _id: string;           // AI assistant identifier (use this for operations)
    type: string;
    name: string;
    path: string;         // Full path like "parent_id.onSuccess.child_id"
    depth: number;        // Nesting level
    parent_id: string | null;
    branchName: string | null;
    hasBranches: boolean;
    branchNames?: string[];
}

/**
 * Result of a mutation operation (update/delete)
 */
export interface MutationResult<T> {
    success: boolean;
    data: T;
    message?: string;
}

/**
 * Branching task types that contain nested tasks in branches
 */
const BRANCHING_TASK_TYPES = new Set([
    'Condition', 'Switch', 'Iterator', 'Loop', 'Transaction', 'Promise', 'State'
]);

/**
 * Check if a task is a branching type (has branches with nested tasks)
 */
export function isBranchingTask(task: Step): boolean {
    return BRANCHING_TASK_TYPES.has(task.type) && 'branches' in task;
}

/**
 * Get branches from a task if it's a branching task
 */
export function getTaskBranches(task: Step): Branches | null {
    if (isBranchingTask(task) && 'branches' in task) {
        return (task as any).branches;
    }
    return null;
}

/**
 * Find a task by _id at any nesting level
 * 
 * @param tasks - Array of tasks to search (typically definition.value.sequence)
 * @param taskId - The unique task _id to find (NOT the workflow engine's id)
 * @param currentPath - Internal: current path being traversed
 * @param parent - Internal: current parent task
 * @param branchName - Internal: current branch name
 * @param depth - Internal: current depth
 * @returns TaskSearchResult with task and location info
 */
export function findTaskById(
    tasks: Step[],
    taskId: string,
    currentPath: string[] = [],
    parent: Step | null = null,
    branchName: string | null = null,
    depth: number = 0
): TaskSearchResult {
    for (const task of tasks) {
        const task_id = task._id || '';
        const taskPath = [...currentPath, task_id];

        if (task._id === taskId) {
            return {
                task,
                path: taskPath,
                pathString: taskPath.join('.'),
                parent,
                branchName,
                depth
            };
        }

        // Recursively search in branches
        const branches = getTaskBranches(task);
        if (branches) {
            for (const [bName, bTasks] of Object.entries(branches)) {
                if (Array.isArray(bTasks)) {
                    const result = findTaskById(
                        bTasks,
                        taskId,
                        [...taskPath, bName],
                        task,
                        bName,
                        depth + 1
                    );
                    if (result.task) {
                        return result;
                    }
                }
            }
        }
    }

    return {
        task: null,
        path: [],
        pathString: '',
        parent: null,
        branchName: null,
        depth: -1
    };
}

/**
 * Find a task by the workflow engine's id (not _id) at any nesting level.
 * Use this when you have an id from the designer's selection mechanism.
 * 
 * @param tasks - Array of tasks to search
 * @param engineId - The workflow engine's id to find
 * @param currentPath - Internal: current path being traversed
 * @param parent - Internal: current parent task
 * @param branchName - Internal: current branch name
 * @param depth - Internal: current depth
 * @returns TaskSearchResult with task and location info
 */
export function findTaskByEngineId(
    tasks: Step[],
    engineId: string,
    currentPath: string[] = [],
    parent: Step | null = null,
    branchName: string | null = null,
    depth: number = 0
): TaskSearchResult {
    for (const task of tasks) {
        const task_id = task._id || '';
        const taskPath = [...currentPath, task_id];

        if (task.id === engineId) {
            return {
                task,
                path: taskPath,
                pathString: taskPath.join('.'),
                parent,
                branchName,
                depth
            };
        }

        // Recursively search in branches
        const branches = getTaskBranches(task);
        if (branches) {
            for (const [bName, bTasks] of Object.entries(branches)) {
                if (Array.isArray(bTasks)) {
                    const result = findTaskByEngineId(
                        bTasks,
                        engineId,
                        [...taskPath, bName],
                        task,
                        bName,
                        depth + 1
                    );
                    if (result.task) {
                        return result;
                    }
                }
            }
        }
    }

    return {
        task: null,
        path: [],
        pathString: '',
        parent: null,
        branchName: null,
        depth: -1
    };
}

/**
 * Find a task by path (e.g., "conditionId.onSuccess.documentId")
 * 
 * @param tasks - Array of tasks to search
 * @param pathString - Dot-separated path to the task
 * @returns TaskSearchResult
 */
export function findTaskByPath(
    tasks: Step[],
    pathString: string
): TaskSearchResult {
    const pathParts = pathString.split('.');
    if (pathParts.length === 0) {
        return {
            task: null,
            path: [],
            pathString: '',
            parent: null,
            branchName: null,
            depth: -1
        };
    }

    // The last part is the task ID we're looking for
    const targetId = pathParts.at(-1);
    if (!targetId) {
        return {
            task: null,
            path: [],
            pathString: '',
            parent: null,
            branchName: null,
            depth: -1
        };
    }
    const result = findTaskById(tasks, targetId);

    if (result.task && result.pathString === pathString) {
        return result;
    }

    return {
        task: null,
        path: [],
        pathString: '',
        parent: null,
        branchName: null,
        depth: -1
    };
}

/**
 * Update a task's property at any nesting level
 * Returns a new tasks array with the update applied (immutable)
 * 
 * @param tasks - Array of tasks
 * @param taskId - _id of task to update (NOT the workflow engine's id)
 * @param updateFn - Function that receives the task and returns updated task
 * @returns MutationResult with new tasks array
 */
export function updateTaskById(
    tasks: Step[],
    taskId: string,
    updateFn: (task: Step) => Step
): MutationResult<Step[]> {
    let found = false;

    const updatedTasks = tasks.map((task): Step => {
        if (task._id === taskId) {
            found = true;
            return updateFn(task);
        }

        // Recursively update in branches
        const branches = getTaskBranches(task);
        if (branches) {
            let branchUpdated = false;
            const updatedBranches: Branches = {};

            for (const [bName, bTasks] of Object.entries(branches)) {
                if (Array.isArray(bTasks)) {
                    const result = updateTaskById(bTasks, taskId, updateFn);
                    updatedBranches[bName] = result.data;
                    if (result.success) {
                        branchUpdated = true;
                        found = true;
                    }
                } else {
                    updatedBranches[bName] = bTasks;
                }
            }

            if (branchUpdated) {
                return { ...task, branches: updatedBranches } as Step;
            }
        }

        return task;
    });

    return {
        success: found,
        data: updatedTasks,
        message: found ? 'Task updated successfully' : `Task not found: ${taskId}`
    };
}

/**
 * Update a specific property on a task using dot notation path
 * 
 * @param tasks - Array of tasks
 * @param taskId - _id of task to update (NOT the workflow engine's id)
 * @param propertyPath - Dot notation path (e.g., "properties.method")
 * @param value - New value to set
 * @returns MutationResult with new tasks array
 */
export function updateTaskProperty(
    tasks: Step[],
    taskId: string,
    propertyPath: string,
    value: unknown
): MutationResult<Step[]> {
    return updateTaskById(tasks, taskId, (task) => {
        const updatedTask = structuredClone(task);

        // Handle property path - convert "properties.X" to "properties.taskSettings.X"
        // EXCEPT for paths that already target taskSettings itself or the type selector
        let actualPath = propertyPath;
        if (propertyPath.startsWith('properties.') &&
            !propertyPath.startsWith('properties.taskSettings') &&
            !propertyPath.startsWith('properties.type')) {
            actualPath = propertyPath.replace('properties.', 'properties.taskSettings.');
        }

        // Set value using dot notation
        const pathParts = actualPath.split('.');
        let current: any = updatedTask;
        for (let i = 0; i < pathParts.length - 1; i++) {
            if (!current[pathParts[i]]) current[pathParts[i]] = {};
            current = current[pathParts[i]];
        }
        const lastPart = pathParts.at(-1);
        if (lastPart) current[lastPart] = value;

        // Also update properties.type if method is being updated
        if (propertyPath === 'properties.method' || propertyPath.endsWith('.method')) {
            if (updatedTask.properties) {
                updatedTask.properties.type = value as string;
            }
        }

        return updatedTask;
    });
}

/**
 * Update MULTIPLE properties on a task in a SINGLE structuredClone pass.
 * Avoids the stale-closure issue of calling updateTaskProperty() sequentially
 * (each call does setDefinition → React batches → only last survives).
 *
 * @param tasks - Array of tasks
 * @param taskId - _id of task to update (NOT the workflow engine's id)
 * @param updates - Array of { path, value } pairs using dot notation
 * @returns MutationResult with new tasks array
 */
export function updateTaskProperties(
    tasks: Step[],
    taskId: string,
    updates: Array<{ path: string; value: unknown }>
): MutationResult<Step[]> {
    return updateTaskById(tasks, taskId, (task) => {
        const updatedTask = structuredClone(task);

        for (const { path: propertyPath, value } of updates) {
            // Same path-remapping logic as updateTaskProperty
            let actualPath = propertyPath;
            if (propertyPath.startsWith('properties.') &&
                !propertyPath.startsWith('properties.taskSettings') &&
                !propertyPath.startsWith('properties.type')) {
                actualPath = propertyPath.replace('properties.', 'properties.taskSettings.');
            }

            // Set value using dot notation
            const pathParts = actualPath.split('.');
            let current: any = updatedTask;
            for (let i = 0; i < pathParts.length - 1; i++) {
                if (!current[pathParts[i]]) current[pathParts[i]] = {};
                current = current[pathParts[i]];
            }
            const lastPart = pathParts.at(-1);
            if (lastPart) current[lastPart] = value;

            // Also sync properties.type when method is updated
            if (propertyPath === 'properties.method' || propertyPath.endsWith('.method')) {
                if (updatedTask.properties) {
                    updatedTask.properties.type = value as string;
                }
            }
        }

        return updatedTask;
    });
}

/**
 * Delete a task by _id at any nesting level
 * Returns a new tasks array with the task removed (immutable)
 * 
 * @param tasks - Array of tasks
 * @param taskId - _id of task to delete (NOT the workflow engine's id)
 * @returns MutationResult with new tasks array
 */
export function deleteTaskById(
    tasks: Step[],
    taskId: string
): MutationResult<Step[]> {
    let found = false;

    // First check if task is at this level
    const taskIndex = tasks.findIndex(t => t._id === taskId);
    if (taskIndex !== -1) {
        found = true;
        const updatedTasks = tasks.filter(t => t._id !== taskId);
        return {
            success: true,
            data: updatedTasks,
            message: 'Task deleted successfully'
        };
    }

    // Recursively check branches
    const updatedTasks = tasks.map((task): Step => {
        const branches = getTaskBranches(task);
        if (branches) {
            let branchUpdated = false;
            const updatedBranches: Branches = {};

            for (const [bName, bTasks] of Object.entries(branches)) {
                if (Array.isArray(bTasks)) {
                    const result = deleteTaskById(bTasks, taskId);
                    updatedBranches[bName] = result.data;
                    if (result.success) {
                        branchUpdated = true;
                        found = true;
                    }
                } else {
                    updatedBranches[bName] = bTasks;
                }
            }

            if (branchUpdated) {
                return { ...task, branches: updatedBranches } as Step;
            }
        }

        return task;
    });

    return {
        success: found,
        data: updatedTasks,
        message: found ? 'Task deleted successfully' : `Task not found: ${taskId}`
    };
}

/**
 * List all tasks with their full path information
 * Traverses all nesting levels
 * 
 * @param tasks - Array of tasks
 * @param parentPath - Internal: current path prefix
 * @param parent_id - Internal: parent task _id
 * @param branchName - Internal: current branch name
 * @param depth - Internal: current depth
 * @returns Array of TaskInfo objects
 */
export function listAllTasks(
    tasks: Step[],
    parentPath: string = '',
    parent_id: string | null = null,
    branchName: string | null = null,
    depth: number = 0
): TaskInfo[] {
    const result: TaskInfo[] = [];

    for (const task of tasks) {
        const task_id = task._id || '';
        const taskPath = parentPath ? `${parentPath}.${task_id}` : task_id;
        const branches = getTaskBranches(task);
        const branchNames = branches ? Object.keys(branches) : undefined;

        result.push({
            _id: task_id,
            type: task.type,
            name: task.name,
            path: taskPath,
            depth,
            parent_id,
            branchName,
            hasBranches: !!branches,
            branchNames
        });

        // Recursively collect tasks from branches
        if (branches) {
            for (const [bName, bTasks] of Object.entries(branches)) {
                if (Array.isArray(bTasks)) {
                    const nestedTasks = listAllTasks(
                        bTasks,
                        `${taskPath}.${bName}`,
                        task_id,
                        bName,
                        depth + 1
                    );
                    result.push(...nestedTasks);
                }
            }
        }
    }

    return result;
}

/**
 * Add a task to a specific location
 * 
 * @param tasks - Array of tasks
 * @param newTask - Task to add
 * @param afterTaskId - Optional: Add after this task _id (null = add to end)
 * @param targetBranchPath - Optional: Path to target branch (e.g., "parent_id.onSuccess")
 * @returns MutationResult with new tasks array
 */
export function addTask(
    tasks: Step[],
    newTask: Step,
    afterTaskId: string | null = null,
    targetBranchPath: string | null = null
): MutationResult<Step[]> {
    // If no target branch, add to root level
    if (!targetBranchPath) {
        if (afterTaskId) {
            const afterIndex = tasks.findIndex(t => t._id === afterTaskId);
            if (afterIndex !== -1) {
                const newTasks = [...tasks];
                newTasks.splice(afterIndex + 1, 0, newTask);
                return { success: true, data: newTasks, message: 'Task added successfully' };
            }
            return { success: false, data: tasks, message: `afterTaskId not found: ${afterTaskId}` };
        } else {
            return { success: true, data: [...tasks, newTask], message: 'Task added successfully' };
        }
    }

    // Parse target branch path: "parent_id.branchName"
    const pathParts = targetBranchPath.split('.');
    if (pathParts.length < 2) {
        return { success: false, data: tasks, message: 'Invalid branch path format' };
    }

    const parentTaskId = pathParts[0];
    const branchName = pathParts[1];

    // Find and update the parent task
    let found = false;
    const updatedTasks = tasks.map((task): Step => {
        if (task._id === parentTaskId) {
            const branches = getTaskBranches(task);
            if (branches && branchName in branches) {
                found = true;
                const branchTasks = branches[branchName] as Step[];
                let newBranchTasks: Step[];

                if (afterTaskId) {
                    const afterIndex = branchTasks.findIndex(t => t._id === afterTaskId);
                    if (afterIndex !== -1) {
                        newBranchTasks = [...branchTasks];
                        newBranchTasks.splice(afterIndex + 1, 0, newTask);
                    } else {
                        newBranchTasks = [...branchTasks, newTask];
                    }
                } else {
                    newBranchTasks = [...branchTasks, newTask];
                }

                return {
                    ...task,
                    branches: { ...branches, [branchName]: newBranchTasks }
                } as Step;
            }
        }

        // Recursively search in nested branches
        const branches = getTaskBranches(task);
        if (branches && !found) {
            let branchUpdated = false;
            const updatedBranches: Branches = {};

            for (const [bName, bTasks] of Object.entries(branches)) {
                if (Array.isArray(bTasks)) {
                    const result = addTask(bTasks, newTask, afterTaskId, targetBranchPath);
                    updatedBranches[bName] = result.data;
                    if (result.success) {
                        branchUpdated = true;
                        found = true;
                    }
                } else {
                    updatedBranches[bName] = bTasks;
                }
            }

            if (branchUpdated) {
                return { ...task, branches: updatedBranches } as Step;
            }
        }

        return task;
    });

    return {
        success: found,
        data: updatedTasks,
        message: found ? 'Task added successfully' : `Branch not found: ${targetBranchPath}`
    };
}

/**
 * Move a task from one location to another
 * 
 * @param tasks - Array of tasks
 * @param taskId - _id of task to move (NOT the workflow engine's id)
 * @param targetBranchPath - Target branch path (null = root level)
 * @param afterTaskId - Add after this task _id (null = add to end)
 * @returns MutationResult with new tasks array
 */
export function moveTask(
    tasks: Step[],
    taskId: string,
    targetBranchPath: string | null = null,
    afterTaskId: string | null = null
): MutationResult<Step[]> {
    // First, find the task
    const searchResult = findTaskById(tasks, taskId);
    if (!searchResult.task) {
        return { success: false, data: tasks, message: `Task not found: ${taskId}` };
    }

    // Remove from current location
    const deleteResult = deleteTaskById(tasks, taskId);
    if (!deleteResult.success) {
        return { success: false, data: tasks, message: 'Failed to remove task from current location' };
    }

    // Add to new location
    const addResult = addTask(deleteResult.data, searchResult.task, afterTaskId, targetBranchPath);
    return addResult;
}

/**
 * Get statistics about the workflow structure
 */
export function getWorkflowStats(tasks: Step[]): {
    totalTasks: number;
    maxDepth: number;
    tasksByType: Record<string, number>;
    branchingTasks: number;
} {
    const allTasks = listAllTasks(tasks);
    const tasksByType: Record<string, number> = {};
    let maxDepth = 0;
    let branchingTasks = 0;

    for (const task of allTasks) {
        tasksByType[task.type] = (tasksByType[task.type] || 0) + 1;
        if (task.depth > maxDepth) maxDepth = task.depth;
        if (task.hasBranches) branchingTasks++;
    }

    return {
        totalTasks: allTasks.length,
        maxDepth,
        tasksByType,
        branchingTasks
    };
}

/**
 * Validate task structure (check for orphans, circular references, etc.)
 */
export function validateTaskStructure(tasks: Step[]): {
    isValid: boolean;
    errors: string[];
    warnings: string[];
} {
    const errors: string[] = [];
    const warnings: string[] = [];
    const seenIds = new Set<string>();

    function validate(taskList: Step[], path: string = ''): void {
        for (const task of taskList) {
            const currentPath = path ? `${path}.${task.id}` : task.id;

            // Check for duplicate IDs
            if (seenIds.has(task.id)) {
                errors.push(`Duplicate task ID found: ${task.id} at ${currentPath}`);
            } else {
                seenIds.add(task.id);
            }

            // Check for missing required fields
            if (!task.id) errors.push(`Task missing ID at ${currentPath}`);
            if (!task.type) errors.push(`Task missing type at ${currentPath}`);
            if (!task.name) warnings.push(`Task missing name at ${currentPath}`);

            // Validate branches
            const branches = getTaskBranches(task);
            if (branches) {
                for (const [bName, bTasks] of Object.entries(branches)) {
                    if (Array.isArray(bTasks)) {
                        validate(bTasks, `${currentPath}.${bName}`);
                    }
                }
            }
        }
    }

    validate(tasks);

    return {
        isValid: errors.length === 0,
        errors,
        warnings
    };
}
